Connectors/Revit/Speckle.Connectors.Revit2023/Speckle.Connectors.Revit2023.csproj
Directory.Build.targets

Done originally in https://github.com/specklesystems/speckle-sharp-connectors/pull/13

Add copying/cleaning if RevitVersion defined and is not a CI build

---

Build/Program.cs

First build the SDK repo to create nugets:
Then build the connectors repo to create a local nuget feed with a custom command:
Then change your local connectors `Directory.Packages.props`
A restore from your IDE will modify package locks and use the new feed for a new version instead of using nuget because the version shouldn't exist yet

download and create local nuget from SDK repo

---

Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitWebViewPlugin.cs

Revit async must be initialized ahead of time in a valid revit context. I had commented this initialization out when upgrading to revit 2025 because revit async was in net framework. I forgot to add this line back after upgrading the package to net standard

Initialize revit async

---

Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Raw/CircularArc3dToSpeckleRawConverter.cs

fixes by retrieving correct midpoint for circular arc with parametrization that is not [0,1]
sample from `HouseDesigner` : https://app.speckle.systems/projects/93200a735d/models/fef1f2b4bf

CNX-103 Autocad: fixes polyline arc segment bug

---

Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Raw/BrepToSpeckleConverter.cs

[CNX-117 : Rhino: failing to send brep spheres, cylinders, paraboloids, ellipsoids, & co.](https://linear.app/speckle/issue/CNX-117/rhino-failing-to-send-brep-spheres-cylinders-paraboloids-ellipsoids)

fix(rhino): checks for null edge trims

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadLayerManager.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/AutocadHostObjectBuilder.cs

and adds extra defensibility around layer naming in acad. 
The issue was that we were not consistently cleaning up the base layer prefix: 
- layer creation would remove `/` chars
- base layer prefix would still contain `/` chars
resulting in all second receives from nested models being borked. 
Also fixes another acad second receive bug, where we would stop purging object layers if we would encounter one with no objects on it.

fix(dui3): cleans up base layer prefix from invalid chars - fixes second receive cleanup issues

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISReceiveBinding.cs
Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/DependencyInjection/ArcGISConnectorModule.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadReceiveBinding.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSelectionBinding.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBinding.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/DependencyInjection/SharedRegistration.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitReceiveBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/RevitConnectorModule.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoReceiveBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/DependencyInjection/RhinoConnectorModule.cs
DUI3/Speckle.Connectors.DUI/Bindings/OperationProgressManager.cs

My initial attempt was on Timers, but I had random behaviors on Autocad, then decided to go with percentage difference checks. Since we round decimals on UI, we don't need to send progress updates less than %1. OperationProgressManager handles it with concurrent dictionary. Open to suggestions, I might do more tests before merging it.

Feat(dui3) Debouncing progress updates

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
Sdk/Speckle.Connectors.Utils/Operations/ReceiveOperation.cs

If the data not in .db, downloading loop twice one for remote transport and one for deserialization, they also overlaps in terms of progress value. Some concurrency happening. We've decided this is good enough for now.

Feat(dui3): CNX-182 upload download progress updates

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadInstanceObjectManager.cs

resolves [CNX-200: Some dynamic blocks are missing nested blocks](https://linear.app/speckle/issue/CNX-200/some-dynamic-blocks-are-missing-nested-blocks)

fix: handles correctly nested dynamic instances (inside other instances)

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Receive/RhinoHostObjectBuilder.cs

Fixes bug where the first created render material was being used instead of none assigned when no render material is found on an object.

fix(rhino): CNX-245 render materials inherited from layer bug

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadBasicConnectorBinding.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadInstanceObjectManager.cs

cause: we were creating definition instances with no objects inside of them, and this was causing acad to throw later down the line on highlighting. 
fixed by: 
- catching the exception for null geometric extents in the highlight logic
- throwing conversion exceptions when creating instances if object count === 0

fix(acad): fatal crash on highlight

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadLayerManager.cs

BEFORE
was crashing if we try to erase active layer for the second receives.
AFTER
switches back to layer `0`

Fix(autocad): Change active layer to 0 if active layer name and will be erased matches

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadBasicConnectorBinding.cs

See the linear for more info. As a result we do not select sub objects on highlight functionality. We will only zoom extend the objects. See gif below

Fix(autocad): Do not select if object to highlight is in Block

---

Connectors/Autocad/Speckle.Connectors.Autocad2022/Speckle.Connectors.Autocad2022.csproj
Connectors/Autocad/Speckle.Connectors.Autocad2023/Speckle.Connectors.Autocad2023.csproj
Connectors/Autocad/Speckle.Connectors.Autocad2024/Speckle.Connectors.Autocad2024.csproj
Connectors/Autocad/Speckle.Connectors.Civil3d2024/Speckle.Connectors.Civil3d2024.csproj
Connectors/Revit/Speckle.Connectors.Revit2022/Speckle.Connectors.Revit2022.csproj
Connectors/Revit/Speckle.Connectors.Revit2023/Speckle.Connectors.Revit2023.csproj
Connectors/Revit/Speckle.Connectors.Revit2024/Speckle.Connectors.Revit2024.csproj
Connectors/Revit/Speckle.Connectors.Revit2025/Speckle.Connectors.Revit2025.csproj
Connectors/Rhino/Speckle.Connectors.Rhino7/Speckle.Connectors.Rhino7.csproj
Connectors/Rhino/Speckle.Connectors.Rhino8/Speckle.Connectors.Rhino8.csproj
Converters/Autocad/Speckle.Converters.Autocad2022/Speckle.Converters.Autocad2022.csproj
Converters/Autocad/Speckle.Converters.Autocad2023/Speckle.Converters.Autocad2023.csproj
Converters/Autocad/Speckle.Converters.Autocad2024/Speckle.Converters.Autocad2024.csproj
Converters/Civil3d/Speckle.Converters.Civil3d2024/Speckle.Converters.Civil3d2024.csproj
Converters/Revit/Speckle.Converters.Revit2022/Speckle.Converters.Revit2022.csproj
Converters/Revit/Speckle.Converters.Revit2023/Speckle.Converters.Revit2023.csproj
Converters/Revit/Speckle.Converters.Revit2024/Speckle.Converters.Revit2024.csproj
Converters/Revit/Speckle.Converters.Revit2025/Speckle.Converters.Revit2025.csproj
Converters/Rhino/Speckle.Converters.Rhino7/Speckle.Converters.Rhino7.csproj
Converters/Rhino/Speckle.Converters.Rhino8/Speckle.Converters.Rhino8.csproj

Adds XX_OR_GREATER to all converter and connector projects:
- Rhino
- Revit
- Acad/Civil
Left ArcGIS out because it has no other version, so it's intention is not as clear.

CXPLA-17 Add XX_OR_GREATER flags to converter/connector projects

---

Connectors/Autocad/Speckle.Connectors.Autocad2024/Speckle.Connectors.Autocad2024.csproj

bug introduced in https://github.com/specklesystems/speckle-sharp-connectors/pull/136/files
adds back a missing semicolon to prevent `GetApp()` from throwing in the connector

fix(autocad2024): define constants missing semicolon

---

Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Raw/CircularArc3dToSpeckleRawConverter.cs
Converters/Rhino/Speckle.Converters.RhinoShared/ToHost/Raw/ArcToHostConverter.cs
Converters/Rhino/Speckle.Converters.RhinoShared/ToHost/Raw/PolyCurveToHostConverter.cs

Previously some polylines with arc segments were resulting in the arc segments being converted with a midpoint = endpoint. This was resulting in failed conversions when receiving in rhino.
I've added some comments on why this seems to happen, as well as an extra check in the arc conversion to use a re-parametrized domain for midpoint calculation.
I've also added a new exception thrown in the rhino polycurve conversion when any segment is not converted to a valid curve.
Tested with multiple autocad files, and receiving them in rhino.

fix(autocad): CNX-274 circulararc conversion now handles edge case

---

Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/TopLevel/SubDObjectToSpeckleTopLevelConverter.cs

Adds SubD sending support in the same way Extrusions are currently supported:
The SubD Object is converted to Brep and sent as such.

CNX-299: Adds support for sending SubD elements as BREPs

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
DUI3/Speckle.Connectors.DUI/Bindings/ISendBinding.cs

1. Disabled send filter updating
2. Replaced send settings property with a method

Rhino send binding fixes

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadColorManager.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadLayerManager.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadMaterialManager.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/Extensions/LayerTableRecordExtensions.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Speckle.Connectors.AutocadShared.projitems

Autocad layer and object can have same `applicationId`. It became visible on sketchup receive since sketchup converter change its context to bake on the way. If you wonder more I can explain more, just find me :)
BEFORE

Fix(autocad): Add "layer_" prefix for layer application ids

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/HostApp/ArcGISColorManager.cs

using this library as reference from @AlexandruPopovici : https://gist.github.com/Aeldrion/48c82912f632eec4c8b9da7394b89c5d
Original:
Before:
After:

fix(arcgis): CNX-307 correct hsv color conversions to rgb

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/DependencyInjection/SharedRegistration.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadInstanceObjectManager.cs

Block instance units were not being converted previously - it was jsut fortuitous that our speckle units strings coincide with `UnitsValue` enums in autocad. This lack of conversion was being exposed when autocad doc units were set to "none", which were correctly mapped to meters in the converter, but kept as none in the instance conversion in the connector.
Now we are injecting the units converter into the instance manager in the connector to fix this problem.
Units after (sent from acad unitless doc):
[https://app.speckle.systems/projects/b53a53697a/models/66aca735ab](https://app.speckle.systems/projects/b53a53697a/models/66aca735ab)

fix(autocad): CNX-272 adds unit conversions to blocks in connector

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoBasicConnectorBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Receive/RhinoHostObjectBuilder.cs

Fix(rhino): Do not store group id in baked object ids

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadColorManager.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Send/AutocadRootObjectBuilder.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoColorManager.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Send/RhinoRootObjectBuilder.cs

After a sync with @AlexandruPopovici , we've decided that the viewer will implement color logic to take into account display behavior by source. 
This behavior is outlined in detail in: https://www.notion.so/speckle/Objects-Colors-3a16d721e9fd46bda5e1b31072a38f29?pvs=4
PR removes hacky logic in autocad and rhino to send definition object colors `by layer` as if `by object`. There is no change in behavior in autocad<>autocad, rhino<>rhino, and autocad<>rhino workflows for color.

chore(autocad/rhino): CNX-357 removes unnecessary definition color logic

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Receive/RhinoHostObjectBuilder.cs

It was on me. While fixing the group highlight performance issue, this scenario skipped..

Fix(rhino): Do not skip first item if it is one-to-one conversion

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Send/ArcGISRootObjectBuilder.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Send/AutocadRootObjectBuilder.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Send/RhinoRootObjectBuilder.cs

We even won't create commit if all objects already `ERROR`ed. Tested in ArcGIS, Rhino and Autocad. Revit can send everything, couldn't find any type of object. But faked it by tweaking the code and it works for sure.
ARCGIS
AUTOCAD
RHINO

Fix(send): Fail fast if all conversion status is ERROR

---

Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterValueExtractor.cs

Aligned V3 with V2 parameter behavior to send any `ElementId` parameter value as the element name where a name exists.
Fixed in V2 with https://github.com/specklesystems/speckle-sharp/pull/3422
Note: Element lookup may be expensive in large commits with many parameters. Should reevaluate this aspect when we get around to a Parameter refactor.
Sample commit with element name parameter values: 
https://app.speckle.systems/projects/b53a53697a/models/d7f7cf1df9

feat(revit): CNX-344 parameter elementid values sent as elements names when available

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SelectionBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/ElementIdHelper.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/RevitHostObjectBuilder.cs

It was a regression on switch from ElementId to UniqueId, since we send report items as UniqueId, it can't parse them directly to ElementId

Fix(revit): regression on switching ElementId to UniqueId

---

Connectors/Revit/Speckle.Connectors.Revit2025/Speckle.Connectors.Revit2025.csproj
Connectors/Revit/Speckle.Connectors.Revit2025/packages.lock.json
Connectors/Revit/Speckle.Connectors.RevitShared.Cef/CefSharpPanel.xaml.cs
Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/RevitConnectorModule.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitCefPlugin.cs

TL;DR > Moved from WebView2 to CefSharp.Wpf.NETCore for Revit 2025
Reviewer should test too!
- Open Revit 2025
- Open relatively big model
- Send model
- TRY to navigate viewer of Revit -> Expectation is not frozen Revit UI and responsive UI interactions
Since the thread management is different between WebView2 and CefSharp, Revit UI was freezing in 2025 bc we moved to WebView2 with it. The source of the problem was we were running SendOperation with `RevitTask.RunAsync` to prevent random `AccessMemoryVialoation` exceptions. And running the operation with `RevitTask.RunAsync` was freezing Revit UI with WebView2.
Thanks to @JR-Morgan and @didimitrie for live fixing effort!

Fix(revit): Reference to CefSharp.Wpf.NETCore for Revit 2025

---

Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Geometry/SpeckleFallbackToHostConversion.cs

This allows to receive objects that have display Value as Points. E.g. Point features from ArcGIS

ACAD: receive points as fallback displayValue

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Config.daml
Connectors/Autocad/Speckle.Connectors.AutocadShared/Plugin/AutocadCommand.cs
Connectors/Revit/Speckle.Connectors.Revit2022/Plugin/Speckle.Connectors.Revit2022.addin
Connectors/Revit/Speckle.Connectors.Revit2023/Plugin/Speckle.Connectors.Revit2023.addin
Connectors/Revit/Speckle.Connectors.Revit2024/Plugin/Speckle.Connectors.Revit2024.addin
Connectors/Revit/Speckle.Connectors.Revit2025/Plugin/Speckle.Connectors.Revit2025.addin
Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitCefPlugin.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitWebViewPlugin.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Plugin/Speckle.Connectors.RhinoCommand.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Plugin/Speckle.Connectors.RhinoPlugin.cs
Converters/ArcGIS/Speckle.Converters.ArcGIS3/ToSpeckle/Raw/PolygonFeatureToSpeckleConverter.cs
Converters/ArcGIS/Speckle.Converters.ArcGIS3/ToSpeckle/Raw/PolylineFeatureToSpeckleConverter.cs
Sdk/Speckle.Connectors.Utils/Connector.cs

- Commands (where existing) are now called `SpeckleBeta`
- Plugin names and panels are now called `Speckle (Beta) for XXX`

CNX-369 Rename all UI elements and commands in v3 connectors

---

Directory.Build.props

Silences warning regarding RIDs for linux in the SQL package that we don't use or need.
This can be fixed properly by updating our SQL package to `2.1.9`, but this has deeper consequences that we don't want to be tackling right now
> Additionally, i also sneakily fixed the product version info to not include the commit sha

chore: Silence SDK1206 warnings for now

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/HostApp/ArcGISColorManager.cs
Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Receive/HostObjectBuilder.cs

In ArcGIS, receive and apply renderMaterials by default, and then, if not found - colors. 
This is due to lack of separate Shared/Rendered mode in ArcGIS
Reported here: https://linear.app/speckle/issue/CNX-373/some-multipatches-are-received-as-red
Outcome if this PR (before/after):

receive materials

---

Converters/Revit/Speckle.Converters.RevitShared/RevitRootToSpeckleConverter.cs

DirectShapes have a category property of type RevitCategory enum. We are assigning category to all converterd revit elements as a string after conversion. This was resulting in an exception for DirectShapes due to type mismatch. This is a POC fix to skip DirectShapes during category assigment. We should revisit DirectShape class to consider changing category type.

fix(Revit):CNX-414 fixes DirectShape category bug

---

DUI3/Speckle.Connectors.DUI.WebView/DUI3ControlWebView.xaml.cs

Reverting the mistake that caused important regression on autocad. TESTED, see gif

Fix(dui3): Use Invoke function instead InvokeAsync

---

DUI3/Speckle.Connectors.DUI/Bridge/BrowserBridge.cs

Somehow, TimeSpan.FromDays(10000) is not good for this. It crashes...... So by default there is no cancellation logic on ActionBlock. I just removed it. @didimitrie let me know if there was a reason adding this CancellationTokenSource..

Fix(dui3): Go with default CancellationTokenSource.None for ActionBlock

---

Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Raw/CircularArc3dToSpeckleRawConverter.cs

I believe we were evaluating mid point with params, seems like it was a wrong approach. `target.EvaluatePoint(midAngle)` seems doing good so far.
BEFORE
AFTER
TRIED TO BREAK IT

Fix(autocad): Evaluate mid point with angle

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitMaterialBaker.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/RevitHostObjectBuilder.cs
Converters/Revit/Speckle.Converters.RevitShared/Helpers/RevitMaterialCacheSingleton.cs
Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/Geometry/MeshConverterToHost.cs

Sent from rhino as meshes -> https://latest.speckle.systems/projects/126cd4b7bb/models/f3b0250890
It doesn't work with Breps, because on converter we don't know the relationship between parent and its list of displayValues.

Feat(revit): CNX-470 add support for layer render materials

---

GitVersion.yml

Prevents increase of commit version when the commit is tagged.
This aligns the tag with the version published, if not there it would +1 the suffix.

fix: Prevent increment when release commit is tagged

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/AutocadHostObjectBuilder.cs

We were passing base object under `displayValue` which was lacking `applicationId`. Instead I pass Brep object as base into `BakeObjectsAsGroup` function.
https://latest.speckle.systems/projects/126cd4b7bb/models/f3b0250890
BEFORE
AFTER

Fix(autocad): Pass parent base object instead base under displayValues to find material

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadBasicConnectorBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/HideWarningsFailuresPreprocessor.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/TransactionManager.cs

- added comments
- added log
- minor change in HideWarningsFailuresPreprocessor

minor changes, logging, comments

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Esri.ArcGISPro.Extensions30.Speckle.targets

Last time I updated the esri file, I had to remove some references to nugets.
This fixed build, but clean was still broken
I thought that this was because of the commenting out I'd done.
Turns out, @AlanRynne has better eyes than I, and found that the clean build has its own references that can be commented out, which fixes clean and rebuilds.
Sorry @KatKatKateryna, this has been an annoyance for both of us, and an easy fix. Thanks @AlanRynne! 🙌

Fixed esri targets file

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitGroupBaker.cs

- Fixes CNX-518 Delete Previous Model Groups on Multiple Receive

Fix(Revit): Delete Previous Model Groups on Multiple Receive

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitGroupBaker.cs
Converters/Revit/Speckle.Converters.RevitShared/RevitRootToSpeckleConverter.cs
Speckle.Connectors.sln

Sending worksetId and worksetName with element
Naming groups after full collection path
Fixes CNX-94
Fixes CNX-542

sending worksetId and workset name + groups named after full path

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/ElementUnpacker.cs
Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/FootPrintRoofToSpeckleTopLevelConverter.cs

see repro in here [CNX-572: Revit Sloped Glazing missing](https://linear.app/speckle/issue/CNX-572/revit-sloped-glazing-missing). 
It's a simple fix: those elements now send.

fix(revit): handles curtain grids hosted on roof elements

---

Converters/Autocad/Speckle.Converters.AutocadShared/AutocadRootToHostConverter.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Civil3dRootToHostConverter.cs

Within conversions, we should be returning "ConversionNotSupportedException" instead of the system "NotSupportedException".

fix: Use ConversionNotSupportedException instead of system one

---

Connectors/Autocad/Speckle.Connectors.Autocad2022/Speckle.Connectors.Autocad2022.csproj
Connectors/Autocad/Speckle.Connectors.Autocad2023/Speckle.Connectors.Autocad2023.csproj
Connectors/Autocad/Speckle.Connectors.Autocad2024/Speckle.Connectors.Autocad2024.csproj
Connectors/Autocad/Speckle.Connectors.Autocad2025/Speckle.Connectors.Autocad2025.csproj
Connectors/Autocad/Speckle.Connectors.Civil3d2024/Speckle.Connectors.Civil3d2024.csproj
Connectors/Rhino/Speckle.Connectors.Rhino7/Speckle.Connectors.Rhino7.csproj
Connectors/Rhino/Speckle.Connectors.Rhino8/Speckle.Connectors.Rhino8.csproj
Converters/Autocad/Speckle.Converters.Autocad2024/Speckle.Converters.Autocad2024.csproj
Converters/Autocad/Speckle.Converters.Autocad2025/Speckle.Converters.Autocad2025.csproj
Directory.Build.props
Directory.Build.targets

> repetition but also much > clarity on what's going on.

fix: Removes some properties from the .targets file and puts them into each csproj

---

DUI3/Speckle.Connectors.DUI/Bindings/ConfigBinding.cs

Related to https://github.com/specklesystems/speckle-server/pull/3163

Feat(Config): Accounts config to keep latest user selected account persistent on UI

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSelectionBinding.cs
Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/HostApp/ArcGISColorManager.cs
Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Send/ArcGISRootObjectBuilder.cs
Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Utils/MapMembersUtils.cs

Treat all Collection-alike layers as GroupLayers (converting to Collections). Otherwise, they are passed to the Converter and justifiably failing.

ArcGIS GroupLayers

---

.github/workflows/main.yml

Re-added installer storage in github actions, but only for release branches.

Adds `store_artifacts` input to build installers trigger

---

Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Parameters/ParameterExtractor.cs

where there's two materials of the same type in the same type, they would override each other; nevertheless, having two plywood layers for one wall is totally acceptable.
note: this is a poc solution for now, as i envision the whole parameter extractor stuff to be properly typed out.

fix(dui3): ensures we don't override structure layers

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoBasicConnectorBinding.cs

fix(rh): scaling incorrectly when copy pasting from one doc to another

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Plugin/Speckle.Connectors.RhinoPlugin.cs

chore(rhino): ensure more robust expiration checks in rhino

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadMaterialUnpacker.cs
Connectors/Autocad/Speckle.Connectors.Civil3d2023/Speckle.Connectors.Civil3d2023.csproj
Connectors/Autocad/Speckle.Connectors.Civil3d2024/Speckle.Connectors.Civil3d2024.csproj
Connectors/Autocad/Speckle.Connectors.Civil3d2025/Speckle.Connectors.Civil3d2025.csproj
Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Raw/DBBodyToSpeckleRawConverter.cs
Converters/Civil3d/Speckle.Converters.Civil3d2023/Speckle.Converters.Civil3d2023.csproj
Converters/Civil3d/Speckle.Converters.Civil3d2024/Speckle.Converters.Civil3d2024.csproj
Converters/Civil3d/Speckle.Converters.Civil3d2025/Speckle.Converters.Civil3d2025.csproj
Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/CorridorHandler.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/ClassPropertiesExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Raw/Point3dCollectionToSpeckleRawConverter.cs

- constants for versions updated
- polyline converter bug
- adds corridor featureline conversion
- adds additional props to subassemblies

chore(civil3d): constants fixes and additional conversion polishing

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs

TLDR; We still use `UniqueId`s.
Main problem was event of deleted objects. We were trying to get `UniqueId` by using provided `ElementId`, but `doc.GetElement(elementId)` can't get any element from deleted `ElementId`. We have to keep remember corresponding `UniqueId`s for `ElementId`s whenever they initially used.

Fix(revit): CNX-657 revit expiration checks seem to be not fully working for

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/ClassPropertiesExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Raw/AlignmentSubentityArcToSpeckleRawConverter.cs

fixes flipped alignment arcs
sample commit:
https://latest.speckle.systems/projects/3f895e614f/models/fff1132068@56b5ffe759

fix(civil3d): alignment arc logic fixed

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/DisplayValueExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/BuiltElements/CivilEntityToSpeckleTopLevelConverter.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/GeneralPropertiesExtractor.cs

For any entity with a basecurve but no display value, adds the basecurves to the display value property instead. The intention is so the parent object is selected in the viewer (instead of the basecurve curve).
sample commit: https://latest.speckle.systems/projects/3f895e614f/models/88370f10da@6fdefc5bc7

fix(civil3d): uses basecurves as display value when no display value exists

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/CorridorDisplayValueExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/CorridorHandler.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/DisplayValueExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ServiceRegistration.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Speckle.Converters.Civil3dShared.projitems

Corridor solids were being attached to every applied subassembly.
This pr converts the assembly used for each region and attaches it in `elements`, as well as the subassemblies (which now contain the display meshes).
Other changes:
- applied assemblies and applied subassemblies now sent as dictionaries instead of Base (a lot more lightweight).
- refactors corridor solid extraction to its own display value extractor class
Sample commit: https://latest.speckle.systems/projects/3f895e614f/models/2533bf268e

fix(civil3d): refactors corridors to only use extracted solids once

---

Converters/Autocad/Speckle.Converters.AutocadShared/AutocadRootToSpeckleConverter.cs
Converters/Autocad/Speckle.Converters.AutocadShared/ServiceRegistration.cs
Converters/Autocad/Speckle.Converters.AutocadShared/Speckle.Converters.AutocadShared.projitems
Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Geometry/ArcToHostConverter.cs
Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Raw/ArcToHostRawConverter.cs

We were previously depending on the speckle arc's plane and start/end angle props to create autocad arcs. Since these props can't be guaranteed to be calculated "correctly" to autocad convention (eg when sent from civil), these dependencies have been removed and recalculated internally.
before:
result:

fix(autocad): arc to host conversions fixed to remove dependency on incoming arc plane and angle props

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Receive/RhinoHostObjectBuilder.cs
Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/TopLevel/RhinoObjectToSpeckleTopLevelConverter.cs

Looks for a `name` property on incoming atomic objects, and bakes rhino objects with a name if one exists.
Motivation: while the name is nice to preserve for multiplayer flows, this property helps a lot when receiving fallback geometry from other apps (esp civil and revit) that would help identify what the original object was.
Also adds `name` property to all rhino objects on send.

feat(rhino): adds names to all objects on bake

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/Civil3dRootToSpeckleConverter.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ServiceRegistration.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Speckle.Converters.Civil3dShared.projitems
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/ExtensionDictionaryExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/GeneralPropertiesExtractor.cs

Example commit: https://app.speckle.systems/projects/b53a53697a/models/719612f9da@72b29b33d0

feat(civil3d): adds missing surface properties and extension dictionaries

---

Connectors/Tekla/Speckle.Connector.Tekla2024/GlobalUsing.cs
Connectors/Tekla/Speckle.Connector.Tekla2024/HostApp/ComponentUnpacker.cs
Connectors/Tekla/Speckle.Connector.Tekla2024/Operations/Send/TeklaRootObjectBuilder.cs
Connectors/Tekla/Speckle.Connector.Tekla2024/ServiceRegistration.cs
Converters/Tekla/Speckle.Converter.Tekla2024/Extensions/SpeckleApplicationIdExtensions.cs
Converters/Tekla/Speckle.Converter.Tekla2024/TeklaRootToSpeckleConverter.cs
Converters/Tekla/Speckle.Converter.Tekla2024/ToSpeckle/Helpers/DisplayValueExtractor.cs

Unpacks components into their children model objects to pass to the converter, and creates group proxies from the components for the root collection

feat(tekla): adds component unpacker to tekla connector

---

README.md

https://linear.app/speckle/issue/CNX-699/update-github-links-to-point-to-v3

Updates README.md to align with main github page

---

Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/Geometry/ArcConverterToHost.cs

fix(revit): removes start angle and end angle reliance in revit arc converter

---

Converters/Revit/Speckle.Converters.RevitShared/Speckle.Converters.RevitShared.projitems
Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/PointcloudTopLevelConverterToSpeckle.cs

https://latest.speckle.systems/projects/3f895e614f/models/12f608f23b

fix(revit): moves pointcloud converter to top level

---

Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Parameters/ParameterDefinitionHandler.cs
Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/MaterialQuantitiesToSpeckle.cs

Models what happened for receive
fix for category being null and tryget

Revit async fix for sending

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
DUI3/Speckle.Connectors.DUI/Bindings/SendBindingUICommands.cs

We were mutating the selectedObjectIds from IdMap. IdMap is a accumulated dictionary that we shouldn't set SelectedObjectIds from it.

Fix(dui3): do not pass selectedobjectids from idmap

---

Build/Consts.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Tekla/Speckle.Connector.Tekla2023/Speckle.Connector.Tekla2023.csproj
Connectors/Tekla/Speckle.Connector.Tekla2024/Speckle.Connector.Tekla2024.csproj
Connectors/Tekla/Speckle.Connector.TeklaShared/Plugin/TeklaPlugin.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/SpeckleTeklaPanelHost.cs
DUI3/Speckle.Connectors.DUI/Bindings/SendBindingUICommands.cs

Update `release/3.0.0` with changes from `dev`

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs

If user scales them it is good because ReplaceRhinoObject is triggered. Otherwise we have to invalidate all cache.

Fix(rhino): Handle unit changes

---

Connectors/Tekla/Speckle.Connector.TeklaShared/HostApp/SendCollectionManager.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/Operations/Send/TeklaRootObjectBuilder.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/ServiceRegistration.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/Speckle.Connectors.TeklaShared.projitems

- Related to [CNX-755](https://linear.app/speckle/issue/CNX-755/create-collections-by-category).
- Grouping of `teklaObject` by `type`.
- `SendCollectionManager.cs` added as done with Revit.
- Tested on the `Basic Steel Model`
- Since grouping is very high-level (not drilling down into property names etc.), chances of `Exceptions` minimal

CNX-755: Create Collections by Category

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ServiceRegistration.cs
Converters/Tekla/Speckle.Converters.TeklaShared/TeklaConversionSettingsFactory.cs
Converters/Tekla/Speckle.Converters.TeklaShared/TeklaToSpeckleUnitConverter.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Helpers/ClassPropertyExtractor.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Helpers/ReportPropertyExtractor.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/TopLevel/ModelObjectToSpeckleConverter.cs

- Related to [CNX-751](https://linear.app/speckle/issue/CNX-751/add-units-to-reportproperties)
- Use of `Tekla.Structures.Datatype` `enums` for units instead of `Tekla.Structures.Drawing`. This makes more sense as the `Drawing` class is more geared to dimension lines, annotations etc. than the model. Here, we also get rid of the `FeetsAndInches`, `CentimetersOrMeters` and `Automatic` enums.
- `hostUnit` from `Tekla.Structures.Datatype.Distance.CurrentUnitType` returns the correct unit set in `Settings > Options > Units and decimals`, but API returns are always mm. Potential mismatch in model units and report property BUT we append the units to each report property.
- `reportProperties` are default mm (or power of). Hence, units appended are hard-coded. Awaiting response and assistance …

CNX-751: Add Units to reportProperties

---

.editorconfig
Connectors/Revit/Speckle.Connectors.RevitShared/ElementIdHelper.cs
Connectors/Rhino/Speckle.Connectors.Rhino8/Speckle.Connectors.Rhino8.csproj
Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoLayerBaker.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoLayerUnpacker.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/CorridorHandler.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/ClassPropertiesExtractor.cs
Converters/Revit/Speckle.Converters.RevitShared/Extensions/CategoryExtensions.cs
Converters/Revit/Speckle.Converters.RevitShared/Helpers/RevitCategoryInfo.cs
Converters/Rhino/Speckle.Converters.Rhino8/Speckle.Converters.Rhino8.csproj

I noticed that we had several obsolete warnings erroneously supressed
This caused a minor incident, where a function was made `Obsolete` in the SDK and we didn't realise we'd missed updating several connectors to use it.
---
This PR re-enables those warnings about using obsolete members
Additionally, I've resolved several violations against host app API members that were made obsolete.
I'm willing to accept us supressing some of these warnings (like in the case of civil, where a member was marked obsolete in 2022, but then was no longer obsolete in 2023).
Host app APIs don't tend to be quite as dev friendly as we'd always like. But for the cases here where there genuine reason to update to avoid obsolete API functions, lets keep on top of it!

Use of obsolete members now generates warning

---

Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaBasicConnectorBinding.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/HostApp/TeklaDocumentModelStore.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/SpeckleTeklaPanelHost.cs

- Double UI
A bit dancing with WPF and triggering `Close` explicitly on unnecessary dialogs helped on not having weird UIs. We also have another `IsInitialized` state that we make it `false` again when the original UI is closed.
- Parenting the dialog 
Connect handle of Plugin dialog to Tekla window which they work together now and our dialog is visible on top of Tekla!
- Document change
We do not necessarily need to close dialogs, just watching document changed event (`ModelLoad`) and trigger UI to refetch state after we read model state as explained below.
- Read/Write model cards
Seems like Tekla API is not friendly on saving things on file. I've introduced new way to handle it and it works as expected so far. @didimitrie was mentioning yesterday we might need similar logic for other …

Fix(tekla): Read write model cards to/from appdata + fixes double UI

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs

Whenever we save something into file, it triggers `DocChangeHandler` since `DataStorage` object has modified. We can safely escape from that to prevent unnecessary `RunExpirationChecks`

Fix(revit): escape fast from doc change event handler after WriteToFile

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSelectionBinding.cs

The loop was designed to iterate through each selected layer, but the function has change to take the list of all layers together. So the loop is redundant and duplicating the results.

removing redundant loop

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Receive/RhinoHostObjectBuilder.cs

Fixes instance receiving in some edge cases 

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitReceiveBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs

No more annoying error
https://github.com/user-attachments/assets/c68c61bc-9a3c-4de7-a185-2875b4757701

Fix(revit): Clear token after every operation to prevent annoying message

---

DUI3/Speckle.Connectors.DUI/Bridge/TopLevelExceptionHandler.cs

When Top level exception toasts fail to display, the exception message is lost
Here, I've adjusted the top level exception handler behaviour to handle toast faliures with an aggregate exception, and provide a better exception message when this occurs.

top level exception handler give a better exception when toasts fail

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadColorBaker.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadInstanceBaker.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadMaterialBaker.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/AutocadHostObjectBuilder.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoInstanceBaker.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Receive/RhinoHostObjectBuilder.cs
DUI3/Speckle.Connectors.DUI.WebView/DUI3ControlWebView.xaml.cs
Sdk/Speckle.Connectors.Common/Instances/IInstanceBaker.cs

There's no way around having to yield to the UI thread to get a status update.  However, we can reduce the number of times we do so.  This is a quick way to have some updates (factor of 50 reduction) but we could do something more inteligent.
Event binding should be reviewing.  This reduces the allocations of the exception handler tasks.  Needs further work though.
https://linear.app/speckle/issue/CNX-854/autocad-receive-performance-totally-tanked

Fix for Autocad receive speed

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoInstanceBaker.cs

Treats the issue described in the linear ticket, but the root cause of the problem is most likely somewhere on the creation side of things (sketchup) OR in rhino's mesh to host converter. 
This is a welcome addition (viewer behaves the same way), where we don't fail instance creation if one object from its definition is missing.

fix(rhino): more lenient creation for failed/partial instances

---

Build/Consts.cs

@adamhathcock not sure we should add `win-x64` to installer assets, can we get rid of from this file?

Chore(navisworks): Add navisworks installer assets

---

Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Plugin/AppUtils.cs

- Add support for Navisworks 2020, 2021, 2022, 2023, 2025, and 2026.
- Throw a NotSupportedException for unsupported versions.

CNX-971 - Update AppUtils.cs to include support for additional versions of Navisworks.

---

Connectors/Navisworks/Speckle.Connectors.NavisworksShared/HostApp/NavisworksMaterialUnpacker.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/NavisworksRootObjectBuilder.cs

This update addresses an issue in the `materialID` logic, where the `renderProxies` material cache was based solely on colour. This caused transparent elements sharing the same colour to incorrectly reuse the same material, leading to rendering errors.
Additionally, the material unpacking routine has been improved to cross-check grouped geometry nodes. Previously, unnamed sibling nodes with no unique properties could result in incorrect overrides or omissions of render proxies for child geometries. The update introduces a new parameter for grouped nodes, ensuring the parent group does not improperly affect the `displayValue` render proxies of its children.
also fixes: CNX-893

fix(Navisworks): CNX-973 Fix: Material ID Logic and Render Proxy Cache

---

Connectors/Navisworks/Speckle.Connectors.Navisworks2020/Speckle.Connectors.Navisworks2020.csproj
Connectors/Navisworks/Speckle.Connectors.Navisworks2021/Speckle.Connectors.Navisworks2021.csproj
Connectors/Navisworks/Speckle.Connectors.Navisworks2022/Speckle.Connectors.Navisworks2022.csproj
Connectors/Navisworks/Speckle.Connectors.Navisworks2023/Speckle.Connectors.Navisworks2023.csproj
Connectors/Navisworks/Speckle.Connectors.Navisworks2024/Speckle.Connectors.Navisworks2024.csproj
Connectors/Navisworks/Speckle.Connectors.Navisworks2025/Speckle.Connectors.Navisworks2025.csproj

- Update the plugin bundle target path to "$(AppData)\Autodesk\ApplicationPlugins\Speckle.Connectors.Navisworks.bundle".
- Update the plugin version content target path to "$(AppData)\Autodesk\ApplicationPlugins\Speckle.Connectors.Navisworks.bundle\Contents\$(NavisworksVersion)".
These changes ensure that the correct paths are used for the Navisworks connector plugin bundle and its version content.

fix(navisworks): Update Navisworks connector plugin bundle target and version content target paths.

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Send/ArcGISRootObjectBuilder.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Send/AutocadRootObjectBaseBuilder.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Operations/Send/CsiRootObjectBuilder.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksSelectionBinding.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksSendBinding.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/NavisworksRootObjectBuilder.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Speckle.Connectors.NavisworksShared.projitems
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Send/RhinoRootObjectBuilder.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/Operations/Send/TeklaRootObjectBuilder.cs
DUI3/Speckle.Connectors.DUI/Models/Card/ModelCardProgress.cs
Sdk/Speckle.Connectors.Common/Builders/IRootObjectBuilder.cs
Sdk/Speckle.Connectors.Common/Operations/SendOperation.cs

Needs to Yield:
- Navisworks
- Rhino
- Tekla
- ETABS
Doesn't need to Yield:
- Autocad
- Revit
ArcGIS is unknown has progress isn't implemented well
Related
https://www.notion.so/speckle/The-Big-Host-App-Threading-Page-14ab78fc7aa6807ca052c6c0869530d2
https://linear.app/speckle/issue/CNX-980/threading-conversion-shows-no-progress

Fix Navisworks and others progress by yielding to UI thread

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs

Notes: this will now expire a sender model card on group/ungroup events, ~~though it's forcing re-conversion of objects that actually did not change (sigh). Nothing is perfect.~~ solved

feat: adds support for group selection events

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs

Invalidates model cards from layer change events (name, colour). Very fast demo: 
https://github.com/user-attachments/assets/8ae646d8-8553-4253-bc9c-88eb47d18370

Dimitrie/cnx 925 Invalidates model cards from layer change events (name, colour)

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/Civil3dRootToSpeckleConverter.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Speckle.Converters.Civil3dShared.projitems
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Raw/Point3dCollectionToSpeckleRawConverter.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/TopLevel/CivilEntityToSpeckleTopLevelConverter.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/TopLevel/CogoPointToSpeckleTopLevelConverter.cs

Cogopoints were not properly supported because the full type name of the class is `Autodesk.**Civil**.DatabaseServices.CogoPoint`, but the inheritance is ` Autodesk.**Autocad**.DatabaseServices.Entity`. 
This means that the top level civil converter is not registering a converter correctly, since cogopoints inherit from autocad entities *not* civil entities and we have no top level entity converter in autocad.
This pr fixes the issue by introducing a top level  `CogoPoint` converter in civil and converting it as a `DataObject` just like all other civil objects. Includes the point name, number, and northing props.
sample model:  https://latest.speckle.systems/projects/2295cb26a0/models/46f44d5e4e
**note** @adamhathcock is making a fix for this on the sdk side to register converters based …

fix(civil): adds top level cogopoint converter

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/SupportedCategoriesUtils.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Filters/RevitCategoriesFilter.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Filters/RevitViewsFilter.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Speckle.Connectors.RevitShared.projitems
Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/RevitElementTopLevelConverterToSpeckle.cs

A bundled set of fixes, related issues. 
1) Categories in the category filter are now down from ~300 to a more legitimate set of approx 120 that we have high confidence are meaningful - specifically model categories. 
2) We pre-filter elements out that do not make sense to convert anyway, based on the same rules of (1). This means **sending empty views does not succeed anymore**, which is legit. 
3) Pruned views to the ones that actually make sense, ignoring schedules and other view types. 
4) Fixed a performance regression introduced with the data object, whereby we'd be endlessly throwing for all elements with an unsupported location property - which can be numerous, eg. floors

Dimitrie/cnx 916 revit all conversions pass nothing fails 

---

Converters/ArcGIS/Speckle.Converters.ArcGIS3/ArcGISConversionSettingsFactory.cs

remove special characters from path after using Uri.AbsolutePath

fix path encoding

---

Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitThreadContext.cs
Sdk/Speckle.Connectors.Common/Threading/ThreadContext.cs

This fixes receive.   It also makes sense to ensure UI/Main thread access is always on the revit message pump

Always run Main stuff on the revit message pump

---

Connectors/Navisworks/Speckle.Connectors.NavisworksShared/DependencyInjection/NavisworksConnectorServiceRegistration.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/HostApp/NavisworksColorUnpacker.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/HostApp/NavisworksMaterialUnpacker.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/NavisworksRootObjectBuilder.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Speckle.Connectors.NavisworksShared.projitems
Converters/Navisworks/Speckle.Converters.NavisworksShared/Helpers/ColorConverter.cs
Converters/Navisworks/Speckle.Converters.NavisworksShared/Speckle.Converters.NavisworksShared.projitems

Currently, all geometry in the Navisworks connector uses RenderMaterialProxies for colour representation. This causes 2D linework to appear uncoloured as it requires ColorProxies instead. This PR adds proper ColorProxy support for 2D elements while maintaining RenderMaterialProxy handling for 3D geometry.
- Add new `ColorProxy` handling for 2D linework
- New simplistic `ComApI.InwSimplePrimitivesCB` callback for primitive type detection
- Implement proxy type detection based on geometry type
- Update root object builder to support both proxy types
- Additionally, refactors `BuildAsync` to reduce complexity and clear method steps

fix(Navisworks): CNX-895 - Add `ColorProxy` Support for 2D Linework

---

Connectors/Navisworks/Speckle.Connectors.NavisworksShared/HostApp/NavisworksDocumentModelStore.cs

Users were prompted to save changes when closing Navisworks, even when no actual modifications had been made to the model. This was occurring because database operations were unnecessarily marking the document as modified.
Investigation revealed several causes:
1. Using `DatabaseChangedAction.Reset` in transactions was marking the document as modified, even for read-only operations
2. Creating transactions to check table existence was triggering the document's dirty state
3. The table existence check was being performed with a transaction unnecessarily, even for read operations
1. Split database operations into discrete functions:
- `DoesTableExist()` - Pure read operation without transactions
- `CreateTable()` - Only uses transaction when creating the table
2. Modified database …

fix(Navisworks): CNX-889 Prevent unnecessary "Save Changes" prompts in Navisworks

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/CorridorDisplayValueExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/GeneralPropertiesExtractor.cs

Fixes a community-submitted bug for baseline points on corridors that throw due to accessing an offset from baseline property. This pr will omit the `offset` property from any point which throws when accessing it.
Also fixes a similar bug in offset alignments, that will throw when accessing `offset` properties, and now skips null corridor solid ids when extracting displayvalues.
Fixes https://github.com/specklesystems/speckle-sharp-connectors/issues/506
Fixes https://github.com/specklesystems/speckle-sharp-connectors/issues/507
- Civil3d converter
before: 
after:
full model with offset alignment:
https://latest.speckle.systems/projects/3f895e614f/models/1737754fb4
corridor with the baseline in the viewer: https://latest.speckle.systems/projects/3f895e614f/models/8c1d9068c3fffc232512c87086d …

fix(civil3d): handles property exceptions for corridor elements

---

Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitCefPlugin.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitExternalApplication.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
DUI3/Speckle.Connectors.DUI/ContainerRegistration.cs

This will be redone in a fast follow PR focusing on Revit properly using the Event Aggregator

This is a workaround for Revit's order of operations when initializing

---

Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedSelectionBinding.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Events/ModelChangedEvent.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Events/SelectionBindingEvent.cs
Connectors/CSi/Speckle.Connectors.CSiShared/HostApp/CsiDocumentModelStore.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Plugin/SpeckleFormBase.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Speckle.Connectors.CSiShared.projitems
Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitEvents.cs
DUI3/Speckle.Connectors.DUI.Tests/Eventing/EventAggregatorTests.cs
DUI3/Speckle.Connectors.DUI/Eventing/OneTimeThreadedEvent.cs
DUI3/Speckle.Connectors.DUI/Eventing/PeriodicThreadedEvent.cs
DUI3/Speckle.Connectors.DUI/Eventing/SpeckleEvent.cs
DUI3/Speckle.Connectors.DUI/Eventing/ThreadedEvent.cs

Add PeriodicThreadedEvent to EA and use it

---

Connectors/CSi/Speckle.Connectors.CSiShared/Operations/Send/CsiRootObjectBuilder.cs
Converters/CSi/Speckle.Converters.CSiShared/Extensions/SpeckleApplicationIdExtensions.cs
Converters/CSi/Speckle.Converters.CSiShared/ToSpeckle/Helpers/SharedPropertiesExtractor.cs

- Link to [CNX-1138](https://linear.app/speckle/issue/CNX-1138/unexpected-object-selection)
- `ETABS` as a building module should not have `REBAR`, `LINK` or `TENDON` objects modelled (i.e. we won't support this workflow). However, for the event that these objects are present in the model, we note the proper conversion success and don't throw a conversion error in the UI.
User is informed of which objects aren't converted and why. Not that the whole conversion fails.
- `GetSpeckleApplicationId` for all possible types
- `NotImplementedException` for `LINK` and `TENDON`
- Marked as `WARNING` in the conversion result

fix(etabs): catch tendon and link objects as warning

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoReceiveBinding.cs

Tested with 
- full receive
- incomplete (cancelled) receive
Properly registers in rhino: 
Tested with 7 & 8

feat(rhino): wraps receive in an undo operation

---

Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Raw/SolidToSpeckleConverter.cs
Sdk/Speckle.Common.MeshTriangulation/MeshGenerator.cs
Sdk/Speckle.Common.MeshTriangulation/TriangleNetTriangulator.cs

- extrude simple holed surfaces in Tekla
- we only extrude if there are exactly 2 surfaces with holes and they face in opposite directions
- in other cases the conversion will fall back to the original logic and will send the 3D Mesh without holes

extrude simple holed surfaces in tekla

---

DUI3/Speckle.Connectors.DUI/Eventing/EventBase.cs

I was seeing a deadlock scenario in Rhino.
One thread was locking `_subscriptions` while publishing events, however in the callback of that event, it was trying to re-subscribe to an event, which was trying to re-enter a lock.
This PR replaces a `yield` enumerable with a list return to ensure that we aren't inside a lock during the executing of publish events.

Event Aggregator Deadlock Fix

---

Sdk/Speckle.Connectors.Common.Tests/CancellationManagerTests.cs
Sdk/Speckle.Connectors.Common/Cancellation/CancellationManager.cs
Sdk/Speckle.Connectors.Common/Operations/ReceiveOperation.cs
Sdk/Speckle.Connectors.Common/Operations/SendOperation.cs

CancellationManager shouldn't ever throw.  This results in error behavior we don't want.  If a card's cancellation is missing, assume it should be cancelled.
can follow repo steps with no errors: https://linear.app/speckle/issue/CNX-1238/rhino-8-restarting-during-an-operation-throws-with-key-not-present-in

fix: (cancellation manager should return cancelled token instead of throwing exception)

---

Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedBasicConnectorBinding.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedSelectionBinding.cs
Connectors/CSi/Speckle.Connectors.CSiShared/HostApp/CsiDocumentModelStore.cs

Etabs Warnings appearing since the #574 fix:
1. `IndexOutOfRangeException` in toolbar dropdown operations 
2. `InvalidOperationException` with cross-thread access to Windows Forms controls
3. "Error in initializing next undo arrays" when performing certain operations
Horrible user experience. NOTE: these dialogs / warnings don't pop up but remain in the background and dont affect send. For the screenshot, the pop-ups were activated:
Rather than changing DUI threading behavior, contained the fix within the CSI:
1. Added `IThreadContext` injection to CSI bindings and store
2. Wrapped CSI API calls in `RunOnMain` to ensure they execute on the main thread
3. Ensured UI updates from timers and event handlers maintain proper thread affinity
Tested both in ETABS 21 and ETABS 22, leaving the …

fix(etabs): ensure csi operations run on main thread to prevent etabs exceptions

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Raw/AlignmentSubentitySpiralToSpeckleRawConverter.cs

Fixes bug where alignment spiral subentity curve points z-value was being assigned to the point's bearing instead of 0.
Fixes #553
no more incorrect alignment spiral curves
- civil converter

fix(civil3d): alignment spiral points set to 0 elevation

---

Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/MaterialQuantitiesToSpeckle.cs

Fixes inconsistent `area` and `volume` measurements between `ParameterExtractor` and `MaterialQuantitiesToSpeckle` by using proper unit-specific scaling instead of derived length factor squaring and cubing.
When extracting material quantities, volumes (e.g.) were being scaled incorrectly by 10⁶ due to improper unit conversion handling.
Fixes [CNX-1277](https://linear.app/speckle/issue/CNX-1277/revit-material-quantities-scaling-bug).
Ensures consistent and accurate material quantity measurements across all Revit elements.
- Replace manual length factor squaring and cubing with unit-specific `Scale()` method in `MaterialQuantitiesToSpeckle`
- Fix incorrect volume unit conversions
- Fix incorrect area unit conversions
- Before: [Commit](https://latest.speckle.systems/projects/99d30f721c/model …

fix(revit): use correct unit scaling for material quantities

---

Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Helpers/PropertiesExtractor.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/TopLevel/ModelObjectToSpeckleConverter.cs

Some tekla object properties are being dynamically attached to the `teklaobject`. Moves these properties to the top level of the `properties` dictionary instead.
Standardizes all object properties
- tekla converter

fix(tekla): moves class properties to top level of properties dictionary

---

Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksSendBinding.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/HostApp/NavisworksColorUnpacker.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/HostApp/NavisworksMaterialUnpacker.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/GeometryNodeMerger.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/NavisworksHierarchyBuilder.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/NavisworksRootObjectBuilder.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/PathConstants.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Speckle.Connectors.NavisworksShared.projitems
Converters/Navisworks/Speckle.Converters.NavisworksShared/Helpers/ElementSelectionHelper.cs
Converters/Navisworks/Speckle.Converters.NavisworksShared/PathConstants.cs

Previously, our GeometryNodeMerger grouped only anonymous geometry nodes with the same parent path. This PR refactors that logic to consider material properties and generate a unique signature for merging. This future-proofs the connector by adding additional properties to the signature generation process without reworking the entire grouping logic.
1. Enhanced Grouping Logic
- `GroupSiblingGeometryNodes` now appends a material-based signature to that path instead of grouping nodes solely by the parent path.
- Nodes with the same parent path and identical material signatures will be merged, reducing redundant geometry.
2. Signature Generation
- New private methods:
- `GenerateSignature(NAV.ModelItem node)`: aggregates relevant material properties (colour, transparency, etc.).
- …

enhancement(Navisworks): CNX-972 - less aggressive object merging

---

DUI3/Speckle.Connectors.DUI/Utils/DiscriminatedObjectConverter.cs

DiscriminatedObjectConverter is effectively a singleton.  To cache types, use a concurrent dictionary rather than changing the lifetime.
stops random errors

fix: Use a concurrent dictionary to cache types since the converter is effectively a singleton

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs

It was throwing error as below. I believe I forgot to bring it back while reverting back thread logic
We got our old logic back

Fix: revert revit task back for highlight view

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/CorridorHandler.cs

Detaches featurelines on corridors so they are api queryable as objects. 
See: https://speckle.community/t/new-connectors-open-beta/10961/48?
makes featurelines api queryable as objects
- civil3d corridor converter

fix(civil): detaches featurelines so they are queryable

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitReceiveBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/LinkedModelsSetting.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/ToSpeckleSettingsManager.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Speckle.Connectors.RevitShared.projitems
Converters/Revit/Speckle.Converters.RevitShared.Tests/ModelCurveArrayToSpeckleConverterTests.cs
Converters/Revit/Speckle.Converters.RevitShared/Settings/RevitConversionSettings.cs
Converters/Revit/Speckle.Converters.RevitShared/Settings/RevitConversionSettingsFactory.cs

Including a setting in the UI to include linked models or not. No actual linked model conversions (yet), just UI functionality. Related to [CNX-1359](https://linear.app/speckle/issue/CNX-1359/have-a-setting-in-ui-whether-include-or-not).
Control over the sending of linked models.
- Created `LinkedModelsSettings.cs` in `Operations/Send/Settings` that implements `ICardSettings`
- Returns from `SendBinding`
https://github.com/user-attachments/assets/4dafbf3e-c530-4ae6-b2fb-c07da8013d3a

feat(revit): linked model settings

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitReceiveBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/LinkedModelsSetting.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/ToSpeckleSettingsManager.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Speckle.Connectors.RevitShared.projitems
Converters/Revit/Speckle.Converters.RevitShared.Tests/ModelCurveArrayToSpeckleConverterTests.cs
Converters/Revit/Speckle.Converters.RevitShared/Settings/RevitConversionSettings.cs
Converters/Revit/Speckle.Converters.RevitShared/Settings/RevitConversionSettingsFactory.cs

Bjorn/cnx 1359 have a setting in UI whether include or not

---

Directory.Packages.props
Local.sln
Sdk/Speckle.Performance/JetbrainsProfiler.cs
Sdk/Speckle.Performance/Speckle.Performance.csproj
Sdk/Speckle.Performance/packages.lock.json
Speckle.Connectors.sln

These create snapshots for dotTrace and dotMemory that can be diff'ed together.
dotTrace or dotMemory should be installed to make sense.
1 - add the reference (this isn't there by default to avoid dependencies in the artifact output)
2 - wrap the relevant code.  In this case, conversion on a receive for all applications:
this creates a trace or snapshot to be loaded and analyzed.
There is usually a pause while an executable is ran to initialize the trace/snapshot
Memory is autoopened and you can view the diff

feat: Perf testing helpers for Jetbrains

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/RevitConnectorModule.cs
Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/DocumentToConvert.cs
Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/SendCollectionManager.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Speckle.Connectors.RevitShared.projitems
Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/Geometry/MeshByMaterialDictionaryToSpeckle.cs

RevitRootObjectBuilder is refactored to align linked models support. We pass `DocumentToConvert` object to send operation which was `ElementId` before.

Feat(revit): linked models POC

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs

Transforms were not correct.
Linked models in correct space.
Use `.Inverse()` of `GetTotalTransform()`
Linked models in the wrong place. Compare Revit (left) with Speckle (right).
Linked models in the correct place.
Before fix -> [model](https://latest.speckle.systems/projects/99d30f721c/models/4623a393ae)
After fix -> [model](https://latest.speckle.systems/projects/99d30f721c/models/38475e4089)
- Linked model instances copied and rotated
- Sent to Speckle
- Validate correct space in 3D occupied by linked instances

fix(revit): transform needed to be inversed

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Filters/RevitCategoriesFilter.cs

Enabling sending of linked models by category.
Choose what categories of a linked model to send.
- Modified `RevitCategoriesFilter` implementation of `RefreshObjectIds` to not filter out `RevitLinkInstance`
- In the for loop for the `linkedModels` added a conditional for `RevitCategoriesFIlter` and filtered as per main model elements
- Overview and comments in [Figma Jam](https://www.figma.com/board/wVIjAWbnOju2yEbtZaLZur/Connectors-v3?node-id=1256-3248&t=HAc9graNFACGHzNJ-4)
https://github.com/user-attachments/assets/f3cd8986-a9bb-4af5-8edd-6f5ce0b13953

feat(revit): linked models send by category

---

Converters/Navisworks/Speckle.Converters.NavisworksShared/ToSpeckle/Raw/GeometryToSpeckleConverter.cs

@kekesidavid reported an issue consuming Navisworks meshes inside Archiacd.
Navisworks is currently sending Meshes using the very old encoding for triangles (using `0` cardinality indicator to mean "triangle" instead using `3`)
I was not expecting any connector to still be sending using the old format. I assume navisworks v2 slipped through, and this has been copied over to v3.

Use 3 instead of 0 for cardinality indicator of triangle faces

---

Build/Program.cs

Some of the dotnet restore was failing on my machine since I have a space in the full path to my repo.

Added quotes escape in build

---

Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/BasicConnectorBinding.cs
Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadBasicConnectorBinding.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedBasicConnectorBinding.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksBasicConnectorBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoBasicConnectorBinding.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaBasicConnectorBinding.cs
DUI3/Speckle.Connectors.DUI/Bindings/AccountBinding.cs
DUI3/Speckle.Connectors.DUI/Bindings/IBasicConnectorBinding.cs
DUI3/Speckle.Connectors.DUI/Models/DocumentModelStore.cs

It is a first pass. And tested via console, it does what it supposed to do.

Feat(accounts): Add remove account to binding

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/SendCollectionManager.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs

Commit structure responds to the presence / absence of linked models (together with the UI setting of course).
If no linked models - flat as normal
If linked models - nested under the root.
- `SendCollectionManager` reacts accordingly
- `RevitRootObjectBuilder` sends a `bool` of `sendLinkedModels` which NOT ONLY checks if the setting is enabled, but if there actually are linked models present in the selection / active session

feat(revit): commit structure

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/RevitConnectorModule.cs
Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/DocumentToConvert.cs
Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/LinkedModelHandler.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Speckle.Connectors.RevitShared.projitems

Refactor how linked models are handled. The major changes focus on processing linked models more efficiently (no unnecessary unpacking and processing of elements) and creating a clearer separation of responsibilities between components (got blurry between `RevitSendBinding` and `RevitRootObjectBuilder`).
Would significantly improves performance when sending models with disabled linked model setting, especially for large projects with many linked models.
Addressed in `RevitSendBinding.cs`.
- Early check of linked model setting
- See comments for better explanation
- Only collects linked model elements IF setting is enabled
Getting some clearer separation of responsibilites between the three classes:
- `LinkedModelHandler` - this is a new class. Dedicated to element collection mechanics …

refactor: linked model helper class and refactor

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/ElementUnpacker.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs

Using converter settings was not true at the beginning because we did not realized that this function also used for cache evict functionality. Need more testing @bjoernsteinhagen

Fix(revit): do not use converter settings in element unpacker

---

Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs

Add transform-specific hashing to properly handle multiple instances of the same linked model. Uses transform properties to create a unique suffix for the applicationId, preventing cached objects from being incorrectly reused across different transform contexts. This also fixes problems observed when trying to recieve back into Revit.
Fixes:
- [CNX-1385](https://linear.app/speckle/issue/CNX-1385/linked-models-instancing)
- [CNX-1434](https://linear.app/speckle/issue/CNX-1434/loading-linked-models-back-in-revit).
Lots.
- Added a `GetTransformHash` method to create unique hashes for transforms (based on `IdGenerator.cs` from `Base`)
- Modified caching logic in `RevitRootObjectBuilder` to consider element transformations
- Added unique transform-specific suffixes to `applicationId` for …

fix(revit): handle multiple linked model instances with transform hashing

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/SendCollectionManager.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs

When sending multiple instances of the same linked model, all elements were being grouped into a single collection named after the last instance. This PR fixes the issue by properly identifying and naming each linked model instance separately, making sure that instances of the same linked model file get appropriate suffixes (_1, _2, etc.) only when multiple instances exist.
FIxes [CNX-1485](https://linear.app/speckle/issue/CNX-1485/segregated-collection-structure-for-multiple-copies-of-the-same-linked).
Users can now clearly identify and navigate elements from different instances of the same linked model in the Speckle viewer, improving the organization and navigation of complex models.
- Added model display name tracking to `RevitRootObjectBuilder` to identify unique linked model …

feat(revit): collection structure for multiple linked model instances 

---

DUI3/Speckle.Connectors.DUI/Models/DocumentModelStore.cs

Got this when loading a Revit file with cards embedded.  Doing investigation for https://linear.app/speckle/issue/CNX-1497/revit-large-models-issues
```
Unhandled Exception: Speckle.Connectors.Revit.Plugin.SpeckleRevitTaskException: Revit operation failed ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at Speckle.Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at …
```

fix(model cards) Avoid multiple enumeration issues when saving if we copy the list first

---

Build/Affected.cs

There was some logic in the CI that if zero connector (slugs) were affected, we'd still build everything.
This conflicts with the ability to publish a nuget for the IFC parser, since I want to just publish the nuget without triggering connector installers

fix(ci): Don't build everything when nothing is detected

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/LinkedModelHandler.cs

Fixed an issue where when sending by views, elements in linked models were being sent regardless of their visibility in the selected view. Now only elements visible in the specified view are included, matching the behavior of the main model.
Fixed [CNX-1491](https://linear.app/speckle/issue/CNX-1491/hiding-categories-in-view-and-linked-models).
Ensures only visible elements in linked models are sent when using view filtering, significantly improving the send operation's accuracy and reducing unnecessary data transfer.
- Added version-specific handling in `LinkedModelHandler` for view filtering:
- For RVT 2024 and RCT 2025: Uses the three-parameter `FilteredElementCollector` constructor to filter visible elements
- For older Revit versions: Checks if the linked model is visible in the view …

fix(revit): respect view visibility in linked models when sending

---

Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Collections/ExpandCollection.cs
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/ComponentUtils.cs
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Operations/Receive/ReceiveAsyncComponent.cs
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Operations/Receive/ReceiveComponent.cs
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Operations/Send/SendAsyncComponent.cs
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Properties/CreateSpeckleDataObject.cs
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Parameters/SpeckleGrasshopperObject.cs
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Parameters/SpecklePropertyGroupWrapper.cs
DUI3/Speckle.Connectors.DUI/Models/DocumentModelStore.cs
Speckle.Connectors.sln

Adds a create data object node.
This requires changing the SpeckleObject class to support one to many relationships: `GeometryBases` property now is a list
This also means now: it's possible to send a mix of geometry objects and data objects from grasshopper...

feat(grasshopper): add create data object node

---

Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Raw/GridToSpeckleConverter.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Raw/PointToSpeckleConverter.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Raw/SolidToSpeckleConverter.cs
Converters/Tekla/Speckle.Converters.TeklaShared/ToSpeckle/Raw/VectorToSpeckleConverter.cs

Tekla always operates on milimeters, just making cosmetic changes on unit changes. The problem reported in the following community post;
https://speckle.community/t/tekla-connector-beta/17347
This PR applies a conversion factor -which we already have a function in our sdk- to the converted geometries.

feat(tekla): apply unit conversion factor

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Send/Filters/RhinoLayersFilter.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Send/Filters/RhinoSelectionFilter.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Speckle.Connectors.RhinoShared.projitems

- Rhino Layers Filter implemented
- Sublayers will be shown with full path like layer01/layer02
- If user selects a sublayer only the direct child elements of that layer will be published
- Users can multiselect layers
- We will probably need to add a new id on UI side, currently "navisworksSavedSets" is used
I don't see Rhino here:

Feat(rhino): send filter for layers

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/LinkedModelHandler.cs

This PR fixes an issue with the view-based filter in Revit where multiple instances of the same linked model were not being handled correctly. Previously, only the visibility of the first linked model instance was considered when determining which elements to include. This meant that if a user had multiple instances of the same linked model with different visibility settings in a view, the system would incorrectly use only the visibility of the first instance for all instances.
The fix leverages our existing transform hash mechanism to identify and match specific linked model instances, ensuring that each instance's visibility in the current view is correctly evaluated.
Fixes [CNX-1490](https://linear.app/speckle/issue/CNX-1490/section-boxes-and-linked-models)
Users can now accurately …

fix(revit): Enable view-based filtering for multiple linked model instances

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs

fixes layer baking from:
- create collection nodes
- receive / expand collection nodes
now objects are baked in their correct layer, not default

fix(grasshopper): fixes layer baking

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CreateCollection.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/ComponentUtils.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveAsyncComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Send/SendAsyncComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Send/SendComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/SpeckleSelectModelComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleUrlModelResourceParam.cs

Renames all outputs to be collection (instead of model / layer) and also publish and load instead of send/receive.
Also makes async the defualt nodes
also adds bool run toggle input to sync send and receive

fix(grasshopper): renames collections, publish, and load

---

DUI3/Speckle.Connectors.DUI/Models/Card/ModelCard.cs

We need to store this info in model card to be able to openUrls for later usage.
We need to align it with sketchup and archicad later (@kekesidavid)

Feat(workspaces): Add workspace slug to model card

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
DUI3/Speckle.Connectors.DUI/Models/DocumentModelStore.cs

It was a regression while fixing the https://linear.app/speckle/issue/CNX-1213/revit-when-moving-between-documents-cards-can-get-lost-between-them

Fix(revit): object tracking for next session

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.cs

forgot to set material source when baking objects 🥲

fix(grasshopper): fixes material baking on objects

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CreateCollection.cs

Just a small optimization in the enumeration of non-collection inputs of the create collection component.
Couldn't reproduce the original issue, as model objects seem to be casting just fine:

chore(grasshopper): improves enumeration of non-collection objects in create collection component

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/SupportedCategoriesUtils.cs

Stacked walls now send. See various attempts here: https://app.speckle.systems/projects/0faf9cbcca/models/9e5bef2441/versions
Tested in revit 2022 and 2023.

fix: allows for stacked walls to be sent

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/FilterObjectsByCollectionPaths.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/ExpandSpeckleObject.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.cs

Before, I was only passing the converted value of a `Base` property of a speckle object.
Now, the value should be a Wrapper Goo, which will be passed even in the event of an unsupported type conversion.
This should allow users to link expand components, and also to explore/reuse unsupport `Base` types.

fix(grasshopper): adds ability to expand base props in Expand Speckle Object component

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleObject.cs

Adds a better tooltip to indicate that only display material, model material, and speckle materials are accepted.

chore(grasshopper): updates tooltip and warning for material input of create speckle object

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleMaterialWrapper.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpecklePropertyGroupWrapper.cs

This casting will *exclude* render materials for now, because I'm avoiding baking anything to doc during cast.
We can later modify this to look for existing materials and pass that through, in the case of a speckle object with a mat that already exists, if needed.

feat(grasshopper): adds casting from speckle object to model object

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveAsyncComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Send/SendAsyncComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Send/SendComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/SpeckleSelectModelComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/GrasshopperReceiveOperation.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs

Adds casting of collections to model layers
should preserve name, path, color, and material (if exists in doc)

feat(grasshopper): adds casting of collections to model layers

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs

Regardless of reference point setting, the model is always published relative to the `ProjectBase`.
- Testing Project: [Revit Reference Point](https://app.speckle.systems/projects/40b659a1da)
- Solves: [CNX-1578](https://linear.app/speckle/issue/CNX-1578/revit-send-reference-setting-is-broken)
Correct spatial transforms applied according to what user set as the reference point.
- In `RevitSendBinding.cs` when collecting the `DocumentToConvert` the main model had a hard-coded `null` as the `DB.Transform`. Using the actual settings fixed the issue.
- For linked models, however, there was an additional step to consider. We needed to combine `mainModelTransform` and the `linkedModel.GetTotalTransform().Inverse` to align the linked model’s elements correctly under the main model’s chosen …

fix(revit): send reference setting is broken

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleObject.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/FilterSpeckleObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/GrasshopperCollectionRebuilder.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/LocalToGlobalMapHandler.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpecklePropertyGroupWrapper.cs

All objects on receive will be decimated into a geometryBase + Speckle Geometry Base wrapped objects, and on send these will be repackaged into DataObjects based on similarity (name and props are the same).
This allows for mutations on individual display value objects (esp in dataobjects) to register as new objects, and also means the send output is consistent with ~only~ dataobjects (instead of a mix) => allows for consistent parsing of gh models by powerbi, automate, etc

fix(grasshopper): repackages objects into data objects on send

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CreateCollection.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Dev/DeconstructSpeckleParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/GrasshopperCollectionRebuilder.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/LocalToGlobalMapHandler.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleMaterialWrapper.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleMaterialWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleObjectWrapper.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleObjectWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleUrlModelResourceParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Speckle.Connectors.GrasshopperShared.projitems

Adds the layer when casting speckle object to model object, if the layer already exists in the doc.
Also adds "Duplicate()" to wrapper classes, and fixes a bunch of mutation issues

feat(grasshopper): add layer to model object casting

---

Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/Geometry/TransformConverterToHost.cs
Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/LocalToGlobalToDirectShapeConverter.cs
Speckle.Connectors.sln

temporary fix for:
https://linear.app/speckle/issue/CNX-1671/rhino2revit-block-transformations-are-broken-again
the fix will throw:
throw new SpeckleException("Transform was not conformal. Skew, non uniform scale is currently not supported.");
if we find a transform with skew
normalization of basis vectors is removed from the transform
applying the transforms is reversed
we will skip the highlighted Breps/Meshes for now:

skip converting breps/mehses with skew transform

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleObject.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs

figured out that in the viewer, if you have a dataobject with the same applicationId as the geometry inside the displayvalue, then the viewer will only apply the material proxy to the first found applicationId (seems random which one it finds first)
solving this by generating a new id for the dataobject always on publish

fix(grasshopper): materials stuff

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleProperties.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleObjectWrapper.ModelObjects.cs

- fixes render material proxy bug in assigning all proxies to the right key on root collection
- fixes getting an object's color and material even if they are from another source (by layer, by material)
https://latest.speckle.systems/projects/3f895e614f/models/43cb043ee7@c92c54a26d

fix(grasshopper): more material bugs

---

Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitReceiveBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/SendRebarsAsSolidSetting.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/SendRebarsAsVolumetricSetting.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/ToSpeckleSettingsManager.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Speckle.Connectors.RevitShared.projitems
Converters/Revit/Speckle.Converters.RevitShared/Helpers/DisplayValueExtractor.cs
Converters/Revit/Speckle.Converters.RevitShared/Settings/RevitConversionSettings.cs
Converters/Revit/Speckle.Converters.RevitShared/Settings/RevitConversionSettingsFactory.cs

Rebar elements had no `DisplayValue` because the standard `get_Geometry()` method returned null for rebars. This PR implements handling for rebar elements with two send modes: centerline and solid, controlled by a toggle: `Send Rebars As Solid` (like in Tekla).
Fixes [CNX-1697](https://linear.app/speckle/issue/CNX-1697/revit-rebar-displayvalue-options-on-send)
Proper visualization of rebar.
- `case` for `DB.Structure.Rebar` elements in the `DisplayValueExtractor`
- Send modes for rebars: centerlines and solids (see below screenshot). Default is to send as centerlines (lighter).
- Refactored common geometry processing logic to reduce code duplication
Speckle model: [link](https://app.speckle.systems/projects/03074a2834/models/181c7a2411@1c4c3f4313)
Speckle model: …

feat(revit): rebar `displayValue` options on send

---

Connectors/Rhino/Speckle.Connectors.Grasshopper7/Speckle.Connectors.Grasshopper7.csproj
Connectors/Rhino/Speckle.Connectors.Grasshopper8/Speckle.Connectors.Grasshopper8.csproj

Required for https://github.com/specklesystems/connector-installers/pull/110

Chore(rhino): Include grasshopper sample files in build output for installers to copy to Components folder

---

Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/Geometry/CurveConverterToHost.cs

An exception was thrown by NurbSpline.CreateCurve
because Revit is stricter than Rhino regarding the input parameters for NURBS curves.
Exception message:
"The multiplicities of other interior knots must be at most degree - 2."
The solution falls back to using displayValue.

fix (Revit) :Hermite Spline conversion when NURBS conversion failing

---

Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/LocalToGlobalToDirectShapeConverter.cs

Fixes [CNX-1825](https://linear.app/speckle/issue/CNX-1825/set-directshape-name).
No immediate value as the `name` doesn't appear in the properties palette. This will be adressed in [CNX-1830](https://linear.app/speckle/issue/CNX-1830/data-exchange-investigations). In this PR, we at least set the name of the `DirectShape` which can be observed using `RevitLookup`.
`SetName` in `LocalToGlobalToDirectShapeConverter.cs`.

feat(revit): set `DirectShape` name

---

Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/BaseCurveExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/DisplayValueExtractor.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/PartDataExtractor.cs

Adds pressure pipe base curve, displayvalue, and partdata.
This was necessary to handle separately because they do not inherit from `Part` as with regular pipes, they inherit from `PressurePart` and therefore need their own case in the basecurveextractor, displayvalueextractor and propertiesextractor
- Note: for basecurve extraction, these methods are only available in Civil3d 2024+
Now you get your pressure pipes with mesh and props.
Community post: https://speckle.community/t/civil-3d-pressure-pipes-not-exported/17841
civil converter
- After: https://latest.speckle.systems/projects/3f895e614f/models/1737754fb4
Sent test file

feat(civil 3d): adds pressure pipe base curve, display value, and partdata

---

Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Geometry/HatchToSpeckleConverter.cs
Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Geometry/RegionToSpeckleConverter.cs
Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Raw/CircularArc2dToSpeckleRawConverter.cs
Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Raw/CircularArc3dToSpeckleRawConverter.cs

Refactors the hatch and region converter to remove unecessary code, and to clean up logic.
Also fixes a big bug:
- previously, hatches were only being converted to the xy plane. now, hatches in other planes are converted properly
commit before pr: https://app.speckle.systems/projects/d58144b502/models/9bd1c080d8@f931cd971b
commit after pr: https://app.speckle.systems/projects/d58144b502/models/9bd1c080d8@002a94941d

refactor(autocad): refactors hatch and region conversion and fixes some bugs

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Dev/DeconstructSpeckleParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleProperties.cs

Adds an option to handle Speckle Properties as an input for `Deconstruct`, which exposes all dictionary entries
Adds a right-click menu item to `Create Properties` node to allow users to create empty properties
Better property UX, to retrieve values quickly
-Deconstruct node
-create properties node
Simple testing of both nodes.
Haven't tested file save behavior.
Undo currently does not undo "create empty Properties" actions.

feat(grasshopper): deconstruct and create empty props

---

Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBaseBinding.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedSendBinding.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksSendBinding.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaSendBinding.cs

It would be great if we can release again after this merge, as it's blocking [CNX-598: Version message](https://linear.app/speckle/issue/CNX-598/version-message)

fix: passes correct arguments to ui on send results

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/ExpandCollection.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveAsyncComponent.cs

Fixes a small bug where we were returning early before setting the UrlModelResource in the async receive node.
Also includes a small change to allow expand collection to parse empty subcollections, since this will probably be expected to match the viewer experience.

fix(grasshopper): url resource set bug on async receive

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoMaterialUnpacker.cs

Trying to avoid a null exception with a null check

Rhino API can return null when not expected

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleVariableParam.cs

- Downstream components not updating when property names change with "Always inherit names" enabled
- When `AlwaysInheritNames` is on and a source params name changes, the param correctly inherits new name but it doesn't trigger necessary events to refresh downstream components
- Fixes [CNX-1998](https://linear.app/speckle/issue/CNX-1998/fix-inheritnames-to-resolve-and-reflect-on-outputparams)
Current and correct names on all referencing components.
Expiring solution on name changes.
https://github.com/user-attachments/assets/0098a39b-3916-44d6-98d4-21d93cff2377
https://github.com/user-attachments/assets/d20a551e-c8cc-42d7-9282-61b39409c7c8

fix (grasshopper): `InheritNames` to resolve and reflect on `OutputParams`

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Extensions/AttributeExtensions.cs

Trying to avoid these null issues as properties could be null

(fix) Rhino: add more null protection

---

Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksSendBinding.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/DependencyInjection/NavisworksConnectorServiceRegistration.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/Filters/NavisworksSavedSetsFilter.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/Filters/NavisworksSavedViewsFilter.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/Filters/SavedItemHelpers.cs
Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Speckle.Connectors.NavisworksShared.projitems

Introduces a new filter for selecting saved views during send operations in the Navisworks connector, enabling users to send only visible elements from saved views. Working with saved views to curate data exchanges is the second most common interaction users perform with Navisworks after Saved Sets, which is already implemented.
It doesn't, at this time, add the selected viewpoint to Canonical views. I don't think other connectors do either??
Only a single saved view can be selected. The `>` separated view names represent the group hierarchy of saved viewpoints.
Additional changes (DRY):
Enhances the build process of hierarchical names for saved items by refactoring code into a reusable helper function, improving maintainability and consistency across filters.

feat(Navisworks): CNX-2009 - Adds saved views filter to Navisworks send operations

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/ExpandCollection.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Dev/DeconstructSpeckleParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleBlockInstance.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleObject.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/GetCollectionObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/HostApp/Helpers.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/LocalToGlobalMapHandler.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Interfaces.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleBlockDefinitionWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleBlockInstanceWrapper.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleBlockInstanceWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleObjectWrapper.ModelObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleObjectWrapper.cs

Refactored inheritance hierarchy to make `SpeckleBlockInstanceWrapper` inherit from `SpeckleObjectWrapper` instead of directly from `SpeckleWrapper`. This removes the need for the `BakingHelpers` static class and simplifies (hopefully) the logic in the collections, validations etc.
Fun time in gh.
- Changed `SpeckleBlockInstanceWrapper` to inherit from `SpeckleObjectWrapper`
- Before and after sketched out [here](https://excalidraw.com/#json=w--IltBklb_l_esrtXYtD,Pb2JBi8PwoTBFjaI5uUuew)
- Added `CreateObjectAttributes()` method to `SpeckleObjectWrapper` with virtual material handling
- Removed `BakingHelpers.CreateObjectAttributes()` static method
- Updated all `Bake()` methods to use the new approach
- Made `Bake()` and `DeepCopy()` methods virtual in `SpeckleObjectWrapper` with proper …

refactor(grasshopper): make `SpeckleBlockInstanceWrapper` inherit from `SpeckleObjectWrapper`

---

Sdk/Speckle.Connectors.Common.Tests/Operations/ReceiveConversionHandlerTests.cs
Sdk/Speckle.Connectors.Common/Operations/ReceiveConversionHandler.cs

These are expected but should up in Seq as errors even though the exceptions aren't logged.  This shouldn't happen.

Don't mark cancelled or conversion exceptions as errors

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/ComponentUtils.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleProperties.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/FilterSpeckleObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/GetObjectProperties.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/PropertyGroupPathsSelector.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/QuerySpeckleObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleObjectPassthrough.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpecklePropertiesPassthrough.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/SpeckleSelectModelComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleMaterialWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleObjectWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpecklePropertyGroupGoo.cs

- Adds the option to open your current URL node in browser, for project, model, or version urls (supposed to help users create new models more easily and to know what they're receiving)
- Sorts components with dividers by adjusting exposure (UI is cleaner)
see above
Opening Urls:
Sorted components:

chore(grasshopper): various touchups

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Wizard/SearchToolStripMenuItem.cs

We reset now list of items by refetching them on closed only if search text is not null.

Fix(gh): reset menu list on closed according to search text

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveAsyncComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveComponent.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/HostApp/Helpers.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/GrasshopperCollectionRebuilder.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/LocalToGlobalMapHandler.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperBlockPacker.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs

These mainly had to do with the receive pipeline. Definition objects were being processed twice - once as regular atomic objects (added to main collection) and once as part of block definitions, causing duplication conflicts during send operations. Definition objects must be converted (for `ConvertedObjectsMap`) but excluded from the main collection hierarchy.
Related to:
- [CNX-2071](https://linear.app/speckle/issue/CNX-2071/type-filters-all-work-as-expected)
- [CNX-2072](https://linear.app/speckle/issue/CNX-2072/sending-objects-file)
Users can now successfully load Rhino models with blocks through Grasshopper, republish them immediately, and see correct colors and full visibility in the Speckle viewer.
- **Fixed definition object duplication**: Added `isDefinitionObject` parameter to …

fix(grasshopper): receive pipeline polish

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleBlockDefinitionPassthrough.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleBlockInstancePassthrough.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleObjectPassthrough.cs

No longer assigns a new appID on passthrough nodes when an input object is mutated.
Requested from community: https://speckle.community/t/no-unique-application-id-when-sending-speckle-blocks-through-grasshopper/18501/6
Allows users working with model objects in Grasshopper to get more reliable change tracking
- speckle object passthrough
- speckle instance passthrough
- speckle definition passthrough
Before:
After:

hotfix(grasshopper): preserve appID on passthrough nodes

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleDataObjectWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleDataObjectWrapperGoo.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleDataObjectWrapperParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Speckle.Connectors.GrasshopperShared.projitems

Created classes needed for DataObject support:
- `SpeckleDataObjectWrapper` - wraps `DataObject` and implements ICollectionObject
- `SpeckleDataObjectWrapperGoo`
- `SpeckleDataObjectParam`
Fixes [CNX-2090](https://linear.app/speckle/issue/CNX-2090/create-dataobject-wrapper-goo-and-param).
Nothing immediate. Foundational work for `DataObejct` support.
- Added `SpeckleDataObjectWrapper` inheriting from `SpeckleWrapper` and implementing `ICollectionObject`
- Added `SpeckleDataObjectWrapperGoo` inheriting from `GH_Goo<SpeckleDataObjectWrapper>`
- Added `SpeckleDataObjectParam` inheriting from `GH_Param<SpeckleDataObjectWrapperGoo>`
- Added TODO comments for future ticket implementations (casting, previewing, baking, loading/publishing, passthrough)

feat(grasshopper): Create DataObject wrapper, goo, and param classes

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleDataObjectWrapper.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleDataObjectWrapperGoo.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleDataObjectWrapperParam.cs

Adds preview for `SpeckleDataObjectWrapper`. Data objects can now be visualized in the viewport like other Speckle object types.
Relates to [CNX-2094](https://linear.app/speckle/issue/CNX-2094/add-previewing)
Users can now see visual previews of `DataObjects`.
- Added `DrawPreview()` and `DrawPreviewRaw()` methods to `SpeckleDataObjectWrapper`
- Implemented `DrawViewportMeshes()` and bounding box calculation in `SpeckleDataObjectWrapperGoo` 
- Implemented preview methods in `SpeckleDataObjectParam` following existing patterns
- Preview logic delegates to existing `SpeckleGeometryWrapper.DrawPreview()` methods

feat(grasshopper): add preview support for `DataObject`

---

Converters/Navisworks/Speckle.Converters.NavisworksShared/DataHandlers/HierarchicalPropertyHandler.cs

Handles properties that are not dictionaries by adding them to a temporary "pseudo class properties" category' and flattens those properties into the main dictionary for easier access.
Also filters specific property names like "ClassName" and "DisplayName".
Source with GUID on ancestor node:
Prior State of flattened and merged leaf node as Speckle Object:
Resolved class properties as result of changes:

fix(Navisworks): include GUIDs and other non-dictionary properties in flat hierarchy

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RevitBuiltInCategoryStore.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Speckle.Connectors.RhinoShared.projitems

Related to [CNX-2182](https://linear.app/speckle/issue/CNX-2182/create-revitbuiltincategory-store).
N/A
- Added `RevitBuiltInCategoryStore` static class
- Static store contains exact Revit enum names verified against API documentation
- No external dependencies added to Rhino connector
- Simple list structure for easy maintenance and extension
- Clean separation - Rhino deals with strings, only Revit connector handles enums

feat: add `RevitBuiltInCategoryStore` for Interop Lite mapper

---

Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Properties/ParameterExtractor.cs

- `GetMaterialIds()` returns nothing on MEP system types
- the material is stored as a parameter
- currently `ParameterExtractor` only extracts `Instance Parameters` and `Type Parameters`
- the current PR adds `System Type Parameters` as well to include MEP materials
Test Commit:
https://app.speckle.systems/projects/c751bae0f6/models/b12f172e0f

feat(revit): extract system type params

---

Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitThreadContext.cs

This should stop Revit from barking as we don't wrap them

Rethrow raw operation exceptions that are probably CancelledTaskExceptions

---

Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/LocalToGlobalToDirectShapeConverter.cs

`LocalToGlobalToDirectShapeConverter` only checked for `builtInCategory` mappings on `DataObject` instances. Rhino geometry objects with mapper-assigned categories (stored as user strings and converted to properties) were not being assigned to the correct Revit categories.
This change extends the category detection logic to work with any `Base` object that has properties containing a `builtInCategory` value, enabling the Rhino-to-Revit mapper functionality for all geometry types.
Users can now assign any Rhino geometry object to specific Revit categories using the mapper, and these objects will be correctly categorized when received in Revit, regardless of geometry type.
- Modified `LocalToGlobalToDirectShapeConverter.cs` to check for `builtInCategory` in any Base object's properties, not …

fix(revit): extend DirectShape category mapping to all geometry objects

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoMapperBinding.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RevitBuiltInCategoryStore.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Mapper/Revit/RevitBuiltInCategoryStore.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Registration/ServiceRegistration.cs
Connectors/Rhino/Speckle.Connectors.RhinoShared/Speckle.Connectors.RhinoShared.projitems
Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/LocalToGlobalToDirectShapeConverter.cs

Rhino-to-Revit object mapping for categories (**LITE**). Users can assign Rhino geometry to specific Revit `BuiltInCategory` values through the UI. The mapping data is stored as user strings on Rhino objects and stored as a prop during send operations.
Related to [Interop Lite Project](https://linear.app/speckle/project/interop-lite-80ec82529c1a).
Interoperability **LITE** between Rhino and Revit by allowing users to pre-assign Revit categories to Rhino objects before publishing.
- Added `RhinoMapperBinding` with category assignment/clearing functionality
- Added `RevitBuiltInCategoryStore` with select hardcoded Revit categories  
https://github.com/user-attachments/assets/4276ce0a-c20f-42d4-b4ba-cfd7498a8b51

feat(rhino): implement Revit category mapper for interop lite

---

Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedSendBinding.cs
Connectors/CSi/Speckle.Connectors.CSiShared/HostApp/Helpers/CsiResultsExtractorFactory.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Operations/Send/CsiRootObjectBuilder.cs
Connectors/CSi/Speckle.Connectors.CSiShared/ServiceRegistration.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Settings/ResultTypeSetting.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Speckle.Connectors.CSiShared.projitems
Converters/CSi/Speckle.Converters.CSiShared/CsiConversionSettings.cs
Converters/CSi/Speckle.Converters.CSiShared/CsiConversionSettingsFactory.cs
Converters/CSi/Speckle.Converters.CSiShared/ToSpeckle/Helpers/CsiFrameForceResultsExtractor.cs
Converters/CSi/Speckle.Converters.CSiShared/ToSpeckle/Helpers/IApplicationResultsExtractor.cs

Integrates analysis results extraction with UI settings system. Users can now select result types through the connector interface, replacing hard-coded extraction logic.
Relates to [CNX-2239](https://linear.app/speckle/issue/CNX-2239/integrate-results-type-dropdown-to-extractor)
Users can dynamically choose which analysis result types to extract without code changes.
- Added `CsiResultsExtractorFactory` for dynamic extractor resolution
- Updated `IApplicationResultsExtractor` with `TargetObjectType` property
- Integrated `ResultTypeSetting` with extractor factory
- Modified `CsiRootObjectBuilder` to use factory-based extraction loop
- Connected UI settings to converter settings pipeline
Result type selection now flows from UI dropdown through settings manager to extractor factory, …

feat(etabs): add UI integration for dynamic result type selection

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoMapperBinding.cs

Added methods to query existing category mappings for objects and layers, enabling the frontend to display current mapping state in the dropdown.
Users can now see what category mappings are already applied to their selected objects/layers. See https://github.com/specklesystems/speckle-connectors-dui/pull/48.
- Added `GetCategoryMappingsForObjects()` method to return a set (i.e. unique list) of categories for given object IDs
- Added `GetCategoryMappingsForLayers()` method to return distinct categories for given layer IDs
https://github.com/user-attachments/assets/c11a855c-6fd7-4750-87e2-e19f3bdc07be

feat(rhino): add category mapping query methods for revit mapper

---

Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitDocumentStore.cs

This avoids locking issues for sharing in Autodesk Work Sharing
This does what Tekla does
This pull request refactors how the `RevitDocumentStore` persists and loads its state, moving away from storing data within the Revit document itself to using a user-scoped SQLite JSON cache. This change simplifies the persistence logic and removes dependencies on Revit's `DataStorage` and threading context.
**Persistence and state management changes:**
* Replaced the use of Revit's `DataStorage` and custom storage schemas for saving and loading state with a user-scoped SQLite JSON cache managed by `ISqLiteJsonCacheManager`. The state is now keyed by the project's unique ID. [[1]](diffhunk://#diff-62f93bf406e759ce39f8825f80bfa0cbe8417b98195028ec9440d8e3b8c4c120L6-R45) …

fix(revit): Revit files persist model card data to a file like Tekla instead of into the file

---

Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Properties/ClassPropertiesExtractor.cs

Fixed a `NullReferenceException` in `ClassPropertiesExtractor.ExtractElementProperties()` that occurred when exporting rooms from linked Revit files. The bug happened because the code was trying to look up worksets from linked model elements using the main document's workset table instead of the element's own document.
The fix ensures we use `element.Document.GetWorksetTable()` instead of `_converterSettings.Current.Document.GetWorksetTable()` and adds proper error handling for edge cases.
Fixes [CNX-2414](https://linear.app/speckle/issue/CNX-2414/revit-operation-failed-on-linked-rooms).
Users can now successfully export rooms from linked files without getting "Revit Operation Failed" errors.
- Updated `ExtractElementProperties()` to use element's own document for workset lookups
- Added …

fix(revit): prevent null reference when extracting workset properties from linked model elements

---

Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/SpeckleRevitTaskException.cs

Fixed UX where users saw generic `Revit operation failed` instead of actionable error messages when publishing failed due to view visibility or unsupported objects.
Users now see clear, actionable error messages like "No supported objects visible. Update publish filter or check publish settings." instead of a generic error, where they don't know what to do -> post something on the forum -> have to send logs etc. etc.
- Updated `SpeckleRevitTaskException` to show inner exception message instead of generic `Revit operation failed`
- Split error handling logic in `RevitRootObjectBuilder` to distinguish between skipped objects vs conversion failures
- Added specific error message for when all objects are filtered out due to view visibility or unsupported categories
**Before:** "Revit …

fix(revit): improve error messages when publishing fails

---

Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoMaterialUnpacker.cs

In cases where there's no `RenderMaterial` on a rhino object, but there is a `Material` applied to a geometry we use the `RenderMaterial.FromMaterial` function to create a new `RenderMaterial` from that `Material` to perform conversion.
But for some reason, this function returns null consistently for our importer.
Perhaps it's because converting things from a headless rhino. Or from windowsless rhino (where some rendering engine parts might not be initalised)
This feels like a bug in Rhino. So I'm tempted to report it to McNeel.
However, I have found this workaround that might work nicely for us.
Using `RenderMaterial.CreateBasicMaterial` as fallback appears to work for the importer.
I'll be honest, I'm not sure I understand the difference between this function and …

fix(rhino): Workaround for rhino materials being null in importer

---

Importers/Rhino/Speckle.Importers.JobProcessor/Domain/FileimportPayload.cs
Importers/Rhino/Speckle.Importers.JobProcessor/JobHandlers/IPCModels.cs
Importers/Rhino/Speckle.Importers.JobProcessor/JobHandlers/RhinoJobHandler.cs
Importers/Rhino/Speckle.Importers.Rhino/Internal/IPCModels.cs
Importers/Rhino/Speckle.Importers.Rhino/Internal/ImporterInstance.cs
Importers/Rhino/Speckle.Importers.Rhino/Internal/Sender.cs
Importers/Rhino/Speckle.Importers.Rhino/Internal/ServiceRegistration.cs
Importers/Rhino/Speckle.Importers.Rhino/Program.cs
Sdk/Speckle.Connectors.Common/HostApplications.cs

Implemented the changes we discussed @gjedlicska @clairekuang for the Rhino importer
I've not touched the other connectors yet, I'll do them in another PR.
This PR adds Mixpanel Send event tracking to the Rhino Importer
It also changes the slugs reported from the importers to include both the file type and "rhino-importer"
so the result is "obj-rhino-importer"
In Mixpanel
in FE
I'm sure we can do something interesting to display this text better in the FE if we wanted

feat(metrics): Add metrics to rhino Importer

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/ExpandCollection.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Dev/DeconstructSpeckleParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/QuerySpeckleObjects.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleOutputParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Speckle.Connectors.GrasshopperShared.projitems

Implements the "Extract parameter" feature for dynamic output parameters. 
Users can now right-click on output parameters from components like Deconstruct, Expand Collection, and Query Objects to extract them as standalone parameters, matching the functionality available in the v2 legacy connector.
- Added `SpeckleOutputParam` class that extends `Param_GenericObject` with extract parameter functionality
- Updated `DeconstructSpeckleParam` to use `SpeckleOutputParam` for all dynamic outputs
- Updated `ExpandCollection` to use `SpeckleOutputParam` for collection child outputs  
- Updated `QuerySpeckleObjects` to use `SpeckleOutputParam` for geometry filter outputs
- Modified `OutputParamWrapper` records to work with `SpeckleOutputParam` …

feat(grasshopper): add extract parameter functionality

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/QuerySpeckleObjects.cs

Fixed an index out of range exception that occurred when users clicked the "+" button to add type-specific outputs (Block Instances, Points, etc.) to the Query Speckle Objects component **while having a path input connected**.
**Note:** this was never working when users piped in a path input.
Users can now use type-specific outputs on Query Speckle Objects with collection paths without errors.
- Replaced `Filters[i - 1]` array indexing with safe param name parsing
- Fixed type-specific outputs to correctly use path-filtered objects instead of the entire collection
- Simplified output logic while maintaining the original code structure
Component goes red with "Index was out of range" error when adding type-specific outputs **with path input**
Component works correctly, showing filtered …

fix(grasshopper): QuerySpeckleObjects crashes with type-specific outputs when path is set

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleBlockDefinitionPassthrough.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleBlockInstancePassthrough.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleDataObjectPassthrough.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleGeometryPassthrough.cs

Temporary fix for bug where mutations on objects with preserved IDs (from `DeepCopy`) are ignored. The serializer caches `ObjectReferences` by `Base.id` and returns stale data instead of recomputing mutated objects.
This was exposed in `SpeckleGeometryPassthrough` where `Name`/`Properties` mutations weren't appearing in the viewer.
**This is a temporary workaround until the proper SDK fix is implemented [CNX-2527](https://linear.app/speckle/issue/CNX-2527/sdk-serializer-ignores-mutations-on-objects-with-preserved-ids-after). PR linked here: [Remove the cache that avoids recalculating IDs from JSON #384](https://github.com/specklesystems/speckle-sharp-sdk/pull/384)**
Fixes [CNX-2233](https://linear.app/speckle/issue/CNX-2233/grasshopper-data-object-mutated-geometry-does-not-get-published) …

fix(grasshopper): clear `Base.id` to force serializer recomputation of mutations

---

Connectors/CSi/Speckle.Connectors.CSiShared/HostApp/CsiDocumentModelStore.cs
Connectors/CSi/Speckle.Connectors.CSiShared/Operations/Send/CsiRootObjectBuilder.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/HostApp/TeklaDocumentModelStore.cs
Connectors/Tekla/Speckle.Connector.TeklaShared/Operations/Send/TeklaRootObjectBuilder.cs
Converters/Civil3d/Speckle.Converters.Civil3dShared/ToSpeckle/Properties/PropertySetExtractor.cs
Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Properties/ParameterExtractor.cs
DUI3/Speckle.Connectors.DUI/Models/DocumentModelStore.cs
Directory.Build.props
Importers/Rhino/Speckle.Importers.Rhino/Internal/Progress.cs
Importers/Rhino/Speckle.Importers.Rhino/Internal/Sender.cs

I noticed several places where we were incorrectly logging interpolated strings.
The standard with structural logging is to use a compile time constant message template, and pass args in to as params
The reason for this is it allows for logs to be easily grouped in seq by template, and parameter values to be searched. It also allows for non-stringified values such as numbers and basic json style structures.
I'll also probably fix CA1727 at some point, but in another PR

Chore(build): Enforce CA2254

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleGeometryWrapper.cs

Fixed `SpeckleBlockInstancePassthrough` outputting empty properties by syncing with the Base object. The issue was that `wrapper.Properties` wasn't kept in sync with `Base["properties"]`.
Fixes bjorn/cnx-2597-block-properties-not-working.
SpeckleBlockInstancePassthrough now correctly outputs properties instead of empty property groups.
- Changed `SpeckleGeometryWrapper.Properties` from a field to a computed property that reads/writes directly from `Base[Constants.PROPERTIES_PROP]`
- Follows the pattern already used in `SpeckleDataObjectWrapper`
Problem was localised to `SpeckleBlockInstance`.
- Tested `SpeckleBlockInstancePassthrough` as well as `SpeckleGeometryWrapper` and `SpeckleDataObjectWrapper` for good measure
- Received objects with props, used the passthrough components to then …

fix(grasshopper): sync SpeckleGeometryWrapper Properties with Base

---

Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Properties/ParameterExtractor.cs

`IsConnected` can only be called on physical connectors. Otherwise they throw an `InvalidOperationException`

Only call `IsConnected` on Physical connectors

---

Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleOutputParam.cs
Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleVariableParam.cs

`SpeckleVariableParam` and `SpeckleOutputParam` were showing up as duplicate "Data" components under `Params/Primitives`. These are foundational classes used internally by variable parameter components and shouldn't be user-facing. Added `GH_Exposure.hidden` to both.
Cleans up the Grasshopper UI by removing two confusing duplicate "Data" parameters that users shouldn't interact with directly.
- Added `GH_Exposure.hidden` to `SpeckleVariableParam`
- Added `GH_Exposure.hidden` to `SpeckleOutputParam`
Build and install the plugin - the duplicate Data components no longer appear under Params/Primitives tab.

fix(grasshopper): hide internal parameter classes from component panel

---

Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Filters/RevitViewsFilter.cs
Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/ToSpeckleSettingsManager.cs

Sparked by an intercom ping (logs in linear ticket). Seems we have an oversight where `SelectedObjectIds` prop in `RevitViewsFilter` was uninitialized (other filters had this in). Should fix the null reference exception when publishing via `RevitViewsFilter`.
`RevitViewsFilter.SelectedObjectIds` was uninitialized when the send operation started. Race condition? The cache eviction logic in `ToSpeckleSettingsManager.EvictCacheForModelCard()` tried to use `SelectedObjectIds` before `RefreshObjectIds()` populated it.
Fixes [CNX-2655](https://linear.app/speckle/issue/CNX-2655/revit-v390-view-filter-crashes-on-send-due-to-null-selectedobjectids)
Avoiding this error:
- Initialize `SelectedObjectIds` property in `RevitViewsFilter` to match `RevitCategoriesFilter` and `DirectSelectionSendFilter`. …

fix(revit): handle null SelectedObjectIds in view filters on send
