specklesystems/speckle-sharp-connectors

- Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Esri.ArcGISPro.Extensions30.Speckle.targets
> Fix on arcgis targets

- Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoLayerManager.cs
> Fix layer traversals

- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SelectionBinding.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitDocumentStore.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitIdleManager.cs
The web view was blank and this fixes swallowed Revit API on wrong thread exceptions
> Use RunAsync for Revits and UI for 2025

- .editorconfig
> suppressed parentheses preferences

- Connectors/Rhino/Speckle.Connectors.Rhino7/Speckle.Connectors.Rhino7.csproj
- Connectors/Rhino/Speckle.Connectors.Rhino8/Properties/launchSettings.json
- Connectors/Rhino/Speckle.Connectors.Rhino8/Speckle.Connectors.Rhino8.csproj
- Directory.Build.targets
Extension is wrong for Rhino 7 and 8 should use common stuff for Rhino
> Fixes for Rhino installers with Rhino8 intro

- Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Raw/BrepToSpeckleConverter.cs
- Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Raw/MeshToSpeckleConverter.cs
- Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Raw/PolylineToSpeckleConverter.cs
I was doing some testing in Rhino to try and reproduce the long send problem,
I needed to send stuff quickly so I did some very low hanging fruit performance optimisations.
Should speed things up by a fair bit.
> quick optimised rhino send

- Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/RevitConnectorModule.cs
> Chore(revit): Disable receive binding for now

- Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
- `RhinoDoc` has an event to track changes on `ObjectAttributes` on `RhinoObject` level, only `LayerIndex` considered as change, we can enrich it later according to needs.
- AutoCAD already tracks layer changes.
> CNX-193 Track layer changes by ModifyObjectAttributes of RhinoObject

- Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadColorManager.cs
- Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadGroupManager.cs
- Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadMaterialManager.cs
- Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/AutocadHostObjectBuilder.cs
- Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Send/AutocadRootObjectBuilder.cs
Mostly added comments and renamed a few things to make them more accurate to what they are referring to, nothing dramatic
> minor suggestions + semantics

- Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/DependencyInjection/ArcGISConnectorModule.cs
- Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/HostApp/ArcGISColorManager.cs
- Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Send/ArcGISRootObjectBuilder.cs
- Converters/ArcGIS/Speckle.Converters.ArcGIS3/ToSpeckle/TopLevel/RasterLayerToSpeckleConverter.cs
- Converters/ArcGIS/Speckle.Converters.ArcGIS3/ToSpeckle/TopLevel/VectorLayerToSpeckleConverter.cs
Adds a color manager class and color proxies on send
> feat(arcgis) : CNX-257 send color proxies

- Sdk/Speckle.Connectors.Utils/Instances/LocalToGlobalUnpacker.cs
makes that `if` simpler/nicer?
> style: better if condition

- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/BeamConversionToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/BraceToSpeckleConverter.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/ColumnConversionToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/CeilingTopLevelConverterToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/ElementTopLevelConverterToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/ExtrusionRoofToSpeckleTopLevelConverter.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/FloorTopLevelConverterToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/FootPrintRoofToSpeckleTopLevelConverter.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/LevelTopLevelConverterToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/RoofBaseToSpeckleTopLevelTopLevelConverter.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/RoomTopLevelConverterToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/TopographyTopLevelConverterToSpeckle.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/WallTopLevelConverterToSpeckle.cs
All non-geometry conversions were missing units: this pr adds them in
> fix(revit): CNX-329 adds units to all relevant conversions

- Converters/Revit/Speckle.Converters.RevitShared/Speckle.Converters.RevitShared.projitems
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/GridTopLevelConverterToSpeckle.cs
They appeared as only lines in viewer. Assuming it is expected as it same in V2.
> Feat(revit): CNX-220 Grid to speckle conversion

- Build/Consts.cs
No code changes, just a small update in the Build.csproj
Must be merged alongside this https://github.com/specklesystems/connector-installers/pull/16
> feat: CNX-347 Includes autocad 2022-2025 in stored artifact for deployment

- Converters/Revit/Speckle.Converters.RevitShared/Helpers/DisplayValueExtractor.cs
closes [CNX-343: Some hosted elements not sent](https://linear.app/speckle/issue/CNX-343/some-hosted-elements-not-sent). It's on me - i introduced this when refactoring not sending light geometry out 😓
> fix(revit): fixes display value extraction problems

- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
[CNX-350: Invalide send hash on Document Units Change](https://linear.app/speckle/issue/CNX-350/invalide-send-hash-on-document-units-change)
> fix(revit): invalidates send cache on doc unit change

- Converters/Rhino/Speckle.Converters.RhinoShared/ToHost/TopLevel/FallbackToHostTopLevelConverter.cs
Resolving Receive of ArcGIS Point features
https://linear.app/speckle/issue/CNX-360/arcgis2rhino-points-not-received
> supports points as fallback in Rhino

- DUI3/Speckle.Connectors.DUI/Bridge/BrowserBridge.cs
- DUI3/Speckle.Connectors.DUI/Models/Card/ReceiverModelCard.cs
Update release branch prior to beta release
> Update release/3.0.0 with changes from dev.

- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitGroupBaker.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitMaterialBaker.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/RevitHostObjectBuilder.cs
purge materials and groups in Revit before update
> purge materials and groups in Revit before update

- Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/SpeckleModule.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitExternalApplication.cs
- Connectors/Rhino/Speckle.Connectors.RhinoShared/Plugin/Speckle.Connectors.RhinoPlugin.cs
- DUI3/Speckle.Connectors.DUI.WebView/DUI3ControlWebView.xaml.cs
- Sdk/Speckle.Autofac/DependencyInjection/SpeckleContainer.cs
Takes care of the Rhino issue where the web view was throwing.  This is because it was never disposed properly.  Now it is along with the container itself
> Dispose Containers (except for Autocad)

- Directory.Build.props
> Use AutomaticallyUseReferenceAssemblyPackages

- Sdk/Speckle.Connectors.Common/Operations/ReceiveOperation.cs
> receive operation fix

- Converters/ArcGIS/Speckle.Converters.ArcGIS3/ArcGISConversionSettingsFactory.cs
https://linear.app/speckle/issue/CNX-501/create-database-in-temp-folder
> CNX-501 Temp folder arcgis

- Converters/ArcGIS/Speckle.Converters.ArcGIS3/ToSpeckle/Raw/GisFeatureToSpeckleConverter.cs
Missing applicationID for PointFeatures
> missing application ID

- Connectors/Tekla/Speckle.Connector.TeklaShared/SpeckleTeklaPanelHost.cs
creates a tracking list of the ui instances and hide one if there is more than one. also adds speckle icon to the panel.
> Dogukan/cnx 679 double UI at the first plugin button click

- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Properties/ClassPropertiesExtractor.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/LevelToSpeckleConverter.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/RevitElementTopLevelConverterToSpeckle.cs
- unifies level generation
- caches level conversion (per send session) 
- levels are now dicts
> WIP: Various level fixes

- Sdk/Speckle.Connectors.Common/Operations/RootObjectSender.cs
> Revert to Send1

- Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaSelectionBinding.cs
> fix(tekla): Update Selection

- Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaSelectionBinding.cs
The discussion about this issue can be find in the following tickets:
https://linear.app/speckle/issue/CNX-982/unhandled-exception-while-executing-getselection
https://linear.app/speckle/issue/CNX-743/selection-null-when-its-over-certain-number
This implementation adds a null check for the parts.
> fix(tekla): Get Selection Exception

- Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
> fix: expired cards on file open

- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/ElementUnpacker.cs
See linear ticket - more info and journaling in there.
> fix: stacked wall duplication when sending by view

- Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Plugin/DockableConnectorPane.cs
Add custom assembly resolve for Navisworks to fix Webview conflicts with NW2025
> Add custom assembly resolve for Navisworks

- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/SupportedCategoriesUtils.cs
- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/TopLevel/RevitElementTopLevelConverterToSpeckle.cs
Makes a known limitation more clear
> fix: ignoring extra categories we cannot support correctly

- Local.sln
- Speckle.Connectors.sln
When I renamed the CI workflow files, I forgot add them back into the sln
> added workflow back into sln

- .github/pull_request_template.md
Amends our pr template to include:
- pr semantic title conventions
- better sections including user value
- pr template
> chore(template): amends pr template to be more descriptive

- Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
Fixes some of the issues seen here: [CNX-1141: Application Crash and Stack Overflow Issue](https://linear.app/speckle/issue/CNX-1141/application-crash-and-stack-overflow-issue)
cc @bimgeek
> fix: exceptions on null layers

- Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoDocumentStore.cs
> fix: isDocumentInit is set to true even on paste operations

- Build/Program.cs
Be more explicit about what solution is being cleaned
> Add deep-clean-local.

- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/ElementUnpacker.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/SupportedCategoriesUtils.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
See linear ticket; both files pass through without errors, as expected.
> fix: ensures we don't go crazy on null categories

- .github/CODEOWNERS
Code ownership for PRs that addresses the specific folders/subfolders will require approval from specific members
> Chore: update code ownership

- Converters/Revit/Speckle.Converters.RevitShared/Helpers/DisplayValueExtractor.cs
Adds the area boundary segments to the display value of an area.
Note: redundant areas will get the boundary segment of the "valid" area they are in.
Now you can see and select areas in the viewer, and receive their geometry in other applications
- revit display value extractor
Before: https://latest.speckle.systems/projects/2295cb26a0/models/8463e46246@e776f64483
After: https://latest.speckle.systems/projects/2295cb26a0/models/8463e46246@bbe0501d61
> fix(revit): adds area boundary segments to display value of area

- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/Geometry/MeshByMaterialDictionaryToSpeckle.cs
now people will be angry they cannot select furniture in some cases.
> feat: moving back to translucid rooms.

- Connectors/Tekla/Speckle.Connector.Tekla2023/Speckle.Connector.Tekla2023.csproj
- Connectors/Tekla/Speckle.Connector.Tekla2023/packages.lock.json
removes runtime identifier for tekla 2023
> fix(tekla): remove runtime identifier

- Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
- Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBaseBinding.cs
- Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedSendBinding.cs
- Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksSendBinding.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
- Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
- Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaSendBinding.cs
It is better on web app to see which version of host app too instead of slug
> Fix: sourceApplication should be app + version

- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/Geometry/PointcloudToSpeckleConverter.cs
Fixes bug in pointcloud conversion where the base plane is erroneously transformed by the pointcloud linked doc transform.
See: https://speckle.community/t/sending-pointcloud-data-from-revit-doesnt-present-all-points/9928/6
This was resulting in pointclouds being sent with no points or partially cut off.
no more faulty pointclouds 
- revit pointcloud converter
Revit objects test file with pointcloud: 
Before: https://latest.speckle.systems/projects/3f895e614f/models/6a8a0f233d@1ad011f2eb
After: https://latest.speckle.systems/projects/3f895e614f/models/6a8a0f233d@78d05e476c
tested by moving the pointcloud around. with the old logic, this does sometimes result in a clipped pointcloud, or no points at all.
> fix(revit): pointcloud plane is incorrectly transformed

- Connectors/Tekla/Directory.Build.targets
- Connectors/Tekla/Speckle.Connector.TeklaShared/Resources/Speckle-Ribbon.xml
fixes minor issues in the ribbon xml copying logic
> fix(tekla): fixes the xml for the ribbon

- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
- Connectors/Tekla/Directory.Build.targets
- Connectors/Tekla/Speckle.Connector.TeklaShared/Resources/Speckle-Ribbon.xml
- DUI3/Speckle.Connectors.DUI/Utils/DiscriminatedObjectConverter.cs
> Release to test Tekla

- Build/Consts.cs
- Converters/Civil3d/Speckle.Converters.Civil3dShared/Helpers/CorridorHandler.cs
> Update dev to release

- .github/workflows/pr.yml
- .github/workflows/release.yml
- DUI3/Speckle.Connectors.DUI.WebView/Speckle.Connectors.DUI.WebView.csproj
- DUI3/Speckle.Connectors.DUI.WebView/packages.lock.json
- DUI3/Speckle.Connectors.DUI/Bridge/BrowserBridge.cs
- DUI3/Speckle.Connectors.DUI/ContainerRegistration.cs
- DUI3/Speckle.Connectors.DUI/Speckle.Connectors.DUI.csproj
- DUI3/Speckle.Connectors.DUI/packages.lock.json
- Importers/Ifc/Speckle.Importers.Ifc/Ara3D.IfcParser/IfcEntity.cs
- Importers/Ifc/Speckle.Importers.Ifc/Ara3D.IfcParser/IfcGraph.cs
- Sdk/Speckle.Common.MeshTriangulation/Speckle.Common.MeshTriangulation.csproj
- Sdk/Speckle.Common.MeshTriangulation/packages.lock.json
- Sdk/Speckle.Connectors.Common/Speckle.Connectors.Common.csproj
- Sdk/Speckle.Connectors.Common/packages.lock.json
- Sdk/Speckle.Converters.Common/Speckle.Converters.Common.csproj
- Sdk/Speckle.Converters.Common/packages.lock.json
to test https://github.com/specklesystems/connector-installers/pull/82
> Test release to test CI changes on connector-installers

- Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/HostApp/ArcGISColorUnpacker.cs
If StoredRenderer exists, it means that layer is using Simple Renderer, and all features will have the same color. No need to extract the color for every feature.
> stop color unpacking

- Importers/Ifc/Speckle.Importers.Ifc/Import.cs
Added IFC source app name for both logging, and model version creation
> Set IFC Source application name 

- Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Raw/MeshToSpeckleConverter.cs
Remove stackalloc usage as it overflows the stack with large meshes
> Remove stackalloc usage as it overflows the stack with large meshes

- Importers/Ifc/Speckle.Importers.Ifc.Tester2/Program.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/NodeExtensions.cs
> Ignore null properties and empty psets

- Converters/Rhino/Speckle.Converters.RhinoShared/ToHost/Helpers/RawEncodingToHost.cs
this is a blind fix: works on bilal's computer, i could not reproduce the issue properly on my machine.
> fix: filter out elems with null geometry

- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/ElementUnpacker.cs
Fixed a `NullReferenceException` that occurred when sending a linked model containing groups. The issue was caused by null elements being passed to the `GroupBy` operation in the `ElementUnpacker.UnpackElements` method.
Fixes [CNX-1444](https://linear.app/speckle/issue/CNX-1444/publishing-linked-model-results-in-object-reference-not-set-to-an).
Specklers can send linked models containing groups without encountering errors.
- Add null element check before `GroupBy` in `ElementUnpacker` to prevent `NullReferenceException`
- Improve robustness when processing groups in linked models
- Handle edge case where group member elements might not resolve properly in linked contexts
See Linear ticket for before changes. Summary video below shows successful send of grouped linked model (previously …
> fix(revit): handle null elements when unpacking linked model groups

- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
This has been an issue since we reverted thread changes. Certain operations like collecting elements in Revit have to run on Revit Thread instead of worker. Otherwise illegal as we are already.
> Fix(revit): illegal attempt to modify document

- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Collections/CollectionPathsSelector.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Collections/FilterObjectsByCollectionPaths.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Operations/Receive/ReceiveAsyncComponent.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Operations/Send/SendComponent.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Properties/FilterPropertiesByPropertyGroupPaths.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Components/Properties/PropertyGroupPathsSelector.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/HostApp/Globals.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Parameters/SpeckleCollectionWrapper.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Parameters/SpeckleGrasshopperObject.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Parameters/SpecklePropertyGroupWrapper.cs
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/Parameters/SpecklePropertyWrapper.cs
Changes the property select by path node to be variable output.
Also includes a refactor of property goos to include path.
> feat(grasshopper): polishes property filtering nodes

- Importers/Ifc/Speckle.Importers.Ifc.Tester2/IfcTester.cs
- Importers/Ifc/Speckle.Importers.Ifc/Ara3D.IfcParser/IfcEntity.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/DataObjectConverter.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/NodeConverter.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/ProjectConverter.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/SpatialStructureConverter.cs
> fix(ifc): Fixed regression with IFC Site geometry not being converted

- Build/Affected.cs
- Importers/Ifc/Speckle.Importers.Ifc.Tester2/IfcTester.cs
- Importers/Ifc/Speckle.Importers.Ifc/Ara3D.IfcParser/IfcEntity.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/DataObjectConverter.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/NodeConverter.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/ProjectConverter.cs
- Importers/Ifc/Speckle.Importers.Ifc/Converters/SpatialStructureConverter.cs
>  Main -> Dev

- Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Operations/Send/Filters/NavisworksSavedSetsFilter.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Filters/RevitCategoriesFilter.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Filters/RevitViewsFilter.cs
- DUI3/Speckle.Connectors.DUI/Models/Card/SendFilter/DirectSelectionSendFilter.cs
- DUI3/Speckle.Connectors.DUI/Models/Card/SendFilter/ISendFilter.cs
To unblock https://github.com/specklesystems/speckle-sharp-connectors/pull/728
> Feat(filters): Add type for send filter

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CollectionPathsSelector.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CreateCollection.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/ExpandCollection.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/FilterObjectsByCollectionPaths.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpecklePropertyGroup.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/ExpandSpeckleObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/LocalToGlobalMapHandler.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Properties/FilterPropertiesByPropertyGroupPaths.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Properties/PropertyGroupPathsSelector.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/HostApp/SpeckleConversionContext.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Speckle.Connectors.GrasshopperShared.projitems
Adds expand object node.
Also refactors previews for collections to be on the collection param.
> feat(grasshopper): expand object node

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CollectionPathsSelector.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/FilterObjectsByCollectionPaths.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/ExpandSpeckleObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpecklePropertyGroupWrapper.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpecklePropertyGroupWrapper.cs
also fixes preview bug in collections
> chore(grasshopper): changes collection path selector to omit input collection name

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CreateCollection.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/ExpandSpeckleObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/GrasshopperCollectionRebuilder.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/GrasshopperColorUnpacker.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/GrasshopperMaterialUnpacker.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/LocalToGlobalMapHandler.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveAsyncComponent.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveComponent.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/HostApp/Helpers.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/HostApp/SpeckleConversionContext.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperColorPacker.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperMaterialPacker.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleCollectionWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleGrasshopperObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleMaterialWrapper.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleMaterialWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Speckle.Connectors.GrasshopperShared.projitems
Adds support for sending and receiving render materials:
- adds material goo and param
- enables baking of material param and of materials when baking objects and layers
- enables casting from model materials and rhino display materials
presentation workflows
a lot of things
> feat(grasshopper): add support for sending and receiving render materials

- Connectors/Revit/Speckle.Connectors.Revit2025/Speckle.Connectors.Revit2025.csproj
> Revit 2025 is now CEF vulnerable

- Sdk/Speckle.Connectors.Common.Tests/Operations/SendOperationTests.cs
- Sdk/Speckle.Connectors.Common/Builders/IRootObjectBuilder.cs
- Sdk/Speckle.Connectors.Common/Operations/SendOperation.cs
- Sdk/Speckle.Connectors.Common/Operations/SendOperationVersionRecorder.cs
An addition as requested by @clairekuang for grasshopper
> Add versionid to send results when creating one

- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
- DUI3/Speckle.Connectors.DUI/Models/DocumentModelStore.cs
Reverts specklesystems/speckle-sharp-connectors#765
> Revert "Fix(revit): object tracking for next session"

- DUI3/Speckle.Connectors.DUI/Bindings/ConfigBinding.cs
Adds config for workspaces. Stores the user selected workspace id to remember for the next session
> Feat: workspaces config

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleProperties.cs
multiple property groups can br created form input trees
> more gh bugs fml

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/SearchToolStripMenuItem.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/SpeckleSelectModelComponent.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Speckle.Connectors.GrasshopperShared.projitems
> Feat(gh): add search to account and project node

- Connectors/Rhino/Speckle.Connectors.Grasshopper7/packages.lock.json
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/packages.lock.json
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleObject.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleProperties.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/FilterSpeckleObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/Receive/ReceiveAsyncComponent.cs
Added another output to the filter objects node, for all of the objects that were filtered out.
useful for presentation workflows maybe
> feat(grasshopper): filter objects node now outputs list of removed objects

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs
removes grouping objects by name and properties on send
> fix(grasshopper): removes dataobject grouping on send

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleObjectPassthrough.cs
- Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Grasshopper/GeometryBaseConverter.cs
Also renames create speckle object to just speckle object
> fix(grasshopper): adds support for pointcloud and hatch

- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/RevitHostObjectBuilder.cs
Fixes [CNX-1707](https://linear.app/speckle/issue/CNX-1707/revit-curves-and-meshes-in-blocks-come-as-duplicated) where block instances with `ITransformable` objects (like polylines, points, etc.) behaving incorrectly when loaded in Revit. Same objects in multiple instances were grouped and duplicated n times (n = number of instances of a block definition).
Problem in how the `TransformTo` method implementation copies the `applicationId` when creating transformed instances, leading to multiple DirectShapes sharing the same definition in the DirectShapeLibrary.
Clean receive.
- Appending short GUID to in `RevitHostObjectBuilder`. Makes no sense in the context of `applicationId` but ensures a clean receive.
@oguzhankoral discuss this hacking of `applicationId`. It smells! …
> fix(revit): ITransformable objects loading in groups and duplicated

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/LocalToGlobalMapHandler.cs
finds units from map object instead of always using meters...
> fix(grasshopper): units bug

- Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitDocumentStore.cs
Threading and holds on the main during a conversion process can result in the wrong document being used when saving model cards.
We only want to save the current cards when it's the right document active.
> Ensure only the correct document is what we save the current model cards to.

- Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaBasicConnectorBinding.cs
Fixes [CNX-1484](https://linear.app/speckle/issue/CNX-1484/create-model-dialog-shows-test-as-suggested-model-name). Create model dialog showed "Test" as suggested model name. It now shows the name of the Tekla model as suggested name.
More relevant / appropriate model name suggestions.
`TeklaBasicConnectorBinding.cs` with more appropriate ``GetDocumentInfo()`.
> feat(tekla): model dialog with suggested model name

- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/RevitHostObjectBuilder.cs
In [CNX-1707](https://linear.app/speckle/issue/CNX-1707/revit-curves-and-meshes-in-blocks-come-as-duplicated), we introduced a modification to the `applicationId` to solve the instancing issue. However, this broke the mapping of `applicationId` in the proxies to the actual objects. For example, Sketchup to Revit workflow was broken: materials were being created in Revit but not assigned to the object(s). 
We will reconsolidate and do this properly:
- [CNX-1797 Revit - Refactor Revit Material Handling System](https://linear.app/speckle/issue/CNX-1797/revit-refactor-revit-material-handling-system)
- [CNX-1769 Revit - Refactoring BakeObjects](https://linear.app/speckle/issue/CNX-1769/revit-refactoring-bakeobjects)
Material assignment on load.
- Moved modification of `applicationId` to before …
> fix(revit): workflow sketchup to revit object material assignment and colors

- Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBaseBinding.cs
- Connectors/CSi/Speckle.Connectors.CSiShared/Bindings/CsiSharedSendBinding.cs
- Connectors/Navisworks/Speckle.Connectors.NavisworksShared/Bindings/NavisworksSendBinding.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
- Connectors/Rhino/Speckle.Connectors.RhinoShared/Bindings/RhinoSendBinding.cs
- Connectors/Tekla/Speckle.Connector.TeklaShared/Bindings/TeklaSendBinding.cs
main (hotfix) version of https://github.com/specklesystems/speckle-sharp-connectors/pull/862
> hotfix: passes correct arguments to ui on send results

- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/SendRebarsAsVolumetricSetting.cs
adding the same note as per Archicad @kekesidavid.
> docs(revit): note for send performance when sending rebar

- Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoLayerBaker.cs
This would be a lot of spam on just a conversion problem
> Change exceptions for not found layers on receive, they should be conversion errors

- Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/AutocadHostObjectBuilder.cs
- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Receive/RevitHostObjectBuilder.cs
- Connectors/Rhino/Speckle.Connectors.RhinoShared/Operations/Receive/RhinoHostObjectBuilder.cs
- Sdk/Speckle.Connectors.Common.Tests/Operations/ReceiveConversionHandlerTests.cs
- Sdk/Speckle.Connectors.Common/Operations/ReceiveConversionHandler.cs
- Sdk/Speckle.Connectors.Common/Operations/ReceiveOperation.cs
and only those that are real are logged to seq
> For Receive conversions, have common path for logging errors

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CreateCollection.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/ExpandCollection.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/CreateSpeckleProperties.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/FilterSpeckleObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/QuerySpeckleObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleBlockDefinitionPassthrough.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleBlockInstancePassthrough.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleObjectPassthrough.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/HostApp/Helpers.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Send/GrasshopperSendOperation.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpecklePropertyGroupGoo.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpecklePropertyGroupGoo.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleBlockDefinitionWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleBlockDefinitionWrapperGoo.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleBlockDefinitionWrapperGoo.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleBlockInstanceWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleBlockInstanceWrapperGoo.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleBlockInstanceWrapperGoo.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleCollectionWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleCollectionWrapperGoo.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleCollectionWrapperGoo.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleMaterialWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleMaterialWrapperGoo.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleObjectWrapper.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleObjectWrapperGoo.ModelObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/Wrappers/SpeckleObjectWrapperGoo.cs
- Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Grasshopper/GeometryBaseConverter.cs
- Converters/Rhino/Speckle.Converters.RhinoShared/ToSpeckle/Raw/InstanceReferenceGeometryToSpeckleConverter.cs
- adds helper methods to create the correct objectwrapper type for speckle objects vs instances
- uses component input and output typing as appropriate for implicit casting
- Removes deep copying in casting. Now all components relying on this should explicitly deep copy wrappers if they are mutating inputs. This should improve any node to node operation that does not mutate objects
- uses generic inputs and outputs for objects and instances. Learning here is that the wrappers just need to be created into their respective goos before setting generic outputs to be registered in their correct type on input
> fix(grasshopper): a bunch of instance vs object casting issues

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/CreateCollection.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Collections/ExpandCollection.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/FilterSpeckleObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/QuerySpeckleObjects.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleBlockDefinitionPassthrough.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/SpeckleGeometryPassthrough.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/HostApp/Helpers.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/GrasshopperCollectionRebuilder.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Operations/Receive/LocalToGlobalMapHandler.cs
Loads data objects.
Also includes changes to these nodes to handle dataobjects:
- expand collection
- query objects
- filter objects
Given the frequent handling of dataobjects + geometry objects, I'm thinking we should introduce an `IAtomicObject:ICollectionObject` interface that enforces properties
> feat(grasshopper): load data objects

- Connectors/Rhino/Speckle.Connectors.Grasshopper7/packages.lock.json
- Connectors/Rhino/Speckle.Connectors.Grasshopper8/packages.lock.json
- Connectors/Rhino/Speckle.Connectors.Rhino7/packages.lock.json
- Connectors/Rhino/Speckle.Connectors.Rhino8/packages.lock.json
- Directory.Packages.props
see https://github.com/specklesystems/speckle-sharp/pull/3724
> Bump GrasshopperAsyncComponent

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Operations/SpeckleSelectModelComponent.cs
- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Parameters/SpeckleUrlModelResourceParam.cs
> chore(grasshopper): renames model link to speckle model

- DUI3/Speckle.Connectors.DUI/Url.cs
> Chore(dui): no more netlify URL

- Connectors/Rhino/Speckle.Connectors.RhinoShared/HostApp/RhinoLayerBaker.cs
Rhino layer names are case-agnostic, and some speckle models (eg revit models with linked models) can have collections with the same name but different capitalization.
This pr makes sure the layer baker cache only works with lowercase key strings
Some models which previously threw exceptions can now be received fully
Successfully received snowdon linked model:
> fix(rhino): models with duplicate collection names can now be received

- Converters/Revit/Speckle.Converters.RevitShared/ToHost/Raw/LocalToGlobalToDirectShapeConverter.cs
Adds reference points for every mesh vertex and reference curves for curves on direct shape meshes and curves
Design coordination isn't great if you can't use your imported geometry as a modelling reference or for drawing gen - eg snapping to your geometry when creating new native model elements, dimensioning in plans and sections. This pr makes reference geometry more usable for files coming in from any connector that doesn't author solids (archicad, navis, autocad/civil, sketchup, blender, etc)
- revit direct shape converter
Before:
After:
Snapping for dimensions in plan and section views
Snapping for new element creation
Tested on curves coming from rhino, and on large navis models (ifc import). haven't done proper performance testing
> feat(revit): adds snapping for mesh vertices and nurbs curves

- Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/Settings/ToSpeckleSettingsManager.cs
> fix(Revit) Use FirstOrDefault more

- Converters/Rhino/Speckle.Converters.RhinoShared/ToHost/Raw/TextEntityToHostConverter.cs
While investigating other text related issues, I discovered issues receiving text into a document with a different unit from the original document.
---
Our normal unit scaling logic in rhino `ToHost` functions relies on a `GeometryBase.Transform` function call in the  `SpeckleToHostGeometryBaseTopLevelConverter` super class.
However, it looks like said `Transform` function (internal name `ON_Geometry_Transform`) does not behave the way we expected for Text entities.
It doesn't appear to scale the text height (despite it being linear units)
Interestingly `TextEntity` does have a different `Transform` overload that does appear to change text height
[`Transform(Transform, DimensionStyle)`](https://github.com/mcneel/rhino3dm/blob/71c63a8c1c87782a13a1b76c825e4b792b36fd09/src/dotnet/opennurbs/op …
> fix(rhino): units scaling for text entities

- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Properties/ParameterDefinitionHandler.cs
This uses the group id of the group to cache group info instead of the parameter name.
This fixes the case where the same param name was used twice in different groups
Found with https://linear.app/speckle/issue/CNX-2572/incorrect-parameter-group-for-some-parameters
> Use Group ID for key of group def instead of a prop name

- Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/Raw/MaterialQuantitiesToSpeckle.cs
> fix (Revit) Make revit exception be a conversion exception

- Connectors/Rhino/Speckle.Connectors.GrasshopperShared/Components/Objects/QuerySpeckleObjects.cs
Fixed a caching bug where the `QuerySpeckleObjects` component's type-specific outputs (Points, Curves, Meshes, etc.) wouldn't refresh when the source collection data changed, even though the main Objects output was updating correctly.
The issue was that the `_filterDict` cache was only being cleared when parameter connections changed, not when the actual data flowing through those parameters changed.
Type-specific outputs now refresh consistently with the main Objects output when collection data changes.
- Clear `_filterDict` cache at the start of each `SolveInstance()` call
- Removed redundant cache count check since cache is always empty
Tested by connecting a changing collection source - all outputs now update simultaneously when source data changes. …
> fix(grasshopper): type-specific outputs not refreshing in `QuerySpeckleObjects` component
